### ISSUE TITLE
Assistant requires basic permissions; points to phone settings

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [endoplasmic/google-assistant#1]
The setup went quite smoothly, minus a nit, but when I want to start a conversation assistant replies with something like "actually I need basic permissions. Just go to your google home app...". Can it be, that the OAuth client tokens must be setup for webapps instead of "other"?

**Comment by eljefedelrodeodeljefe** [comment]
Hmm. 2 things, I believe the permission Google requires has just not propagated, but it is described [here](https://developers.google.com/assistant/sdk/prototype/getting-started-other-platforms/config-dev-project-and-account). Pointing to it strongly might be good since google assistants help here is not really helpful.

Suggestion: maybe branching for the web or installed version would be a good feature for this library, but is unrelated to the problem.

**Comment by endoplasmic** [comment]
Glad things went smooth! 

I actually *do* link to that page in the "Installation" section, but I went ahead and moved it to *before* the mention of the `npm install google-assistant` part. Hopefully people see it a little better

**Comment by eljefedelrodeodeljefe** [comment]
Now, I am seeing it. It's kinda cumbersome on google since I actually made the changes, but it has not propagated.
