### ISSUE TITLE
deprecated grpc@1.24.11

### ISSUE THREAD

**Issue by arturzangiev** [endoplasmic/google-assistant#101]
When try to install it I receive this warning and the installation not proceeding further:

npm WARN deprecated grpc@1.24.11: This library will not receive further updates other than security fixes. We recommend using @grpc/grpc-js instead.

**Comment by bugsounet** [comment]
Hi, I use grpc-js since now 1y 1/2 with no problem (and with electron) 

@endoplasmic will not really interested with this library maybe he will apply now ;)

**Comment by arturzangiev** [comment]
Strange I tried it, but still get the same warning when installing google-assistant. Also wanted to know are you using mac or windows? It looks like it is installing on unix based systems, but for some reason I am stuck with installation on windows.

**Comment by bugsounet** [comment]
```
pi@Raspberry:~/@bugsounet/google-assistant $ npm install 
added 47 packages, and audited 48 packages in 4s                                                                                                                                                                                                3 packages are looking for funding
run `npm fund` for details
found 0 vulnerabilities
pi@Raspberry:~/@bugsounet/google-assistant $ cat package.json | grep grpc
"@grpc/grpc-js": "^1.2.5"
```

no problem ;)

**Comment by endoplasmic** [comment]
I went ahead an bumped the version to v0.7.0, axed the old `grpc` module and replaced it with `@grpc/grpc-js`.

Let me know if you're still seeing any problems.
