### ISSUE TITLE
Want to build an "answering machine"

### ISSUE THREAD

**Issue by frankhommers** [endoplasmic/google-assistant#103]
Hi there,

I know this isn't really an issue for this lib. But since you are an expert on this subject, I might as well ask it here.

I want to build some sort of an answering machine (saving the recording to a cloud service). 
I want to use this for recording my own ideas. The workflow I imagine is:

Hey Google, Record an idea.
-Then I express my idea in speech-

After that I want to be able to access the audio file of my spoken words (Not only the Speech-To-Text text).

Would this be possible with this lib? 
And if so can you give me some pointers?

Thanks!

**Comment by endoplasmic** [comment]
Hey, thanks for the question and I think what you're trying to do is build an `Action` for the Google Assistant.

[Here is a codelab](https://developers.google.com/codelabs/actions-builder-1#0) that walks you through the process of creating custom actions for the Assistant.

Maintaining the audio part of your request would have to be done in parallel or something (or if you've got the setting turned on, you can [listen to your old audio requests](https://support.google.com/websearch/answer/6030020?hl=en&co=GENIE.Platform%3DDesktop) within your account settings.

**Comment by frankhommers** [comment]
Hmm.. That maintaining of the audio requests is the key to my idea. 

Because my ideas are usually super technical, it's something which Google always interprets wrong when using their speech-to-text.

Do you know if there is a Google API to access those old audio requests?

**Comment by frankhommers** [comment]
I guess there is none... Only some selenium based scrapers

**Comment by frankhommers** [comment]
Thanks for the info for now.
