### ISSUE TITLE
Shouldn't continueConversation be set to false again?

### ISSUE THREAD

**Issue by Pajn** [endoplasmic/google-assistant#11]
In the conversation component continueConversation is set to true when DIALOG_FOLLOW_ON is received but it isn't set back to false agan which I think it should do when CLOSE_MICROPHONE is received.

I'm having problems with the assistant continues sometimes when it shouldn't which I think could be related to this.

**Comment by endoplasmic** [comment]
Could you give me an example of what you're saying that requires there follow-up and your response after?

**Comment by Pajn** [comment]
Hmm, I can't reproduce it reliably but "hey google" seems like a big source of problems, but it may be that google does something special with that to avoid thinking that a repeated wakeword is said to it.
I added a timeout where I close the conversation if I don't get "end-of-utterance" which seems to make it much more reliable in those cases so I'm closing this. Sorry for the noice!
