### ISSUE TITLE
Invalid 'audio_in': too long.

### ISSUE THREAD

**Issue by eouia** [endoplasmic/google-assistant#12]
```
[running mic-speaker.js]
Say something!
Conversation Error: { Error: Invalid 'audio_in': too long.
    at ClientDuplexStream._emitStatusIfDone (/.../node_modules/grpc/src/node/src/client.js:270:19)
    at ClientDuplexStream._receiveStatus (/.../node_modules/grpc/src/node/src/client.js:248:8)
    at /.../node_modules/grpc/src/node/src/client.js:772:12 code: 3, metadata: Metadata { _internal_repr: {} } }
^C

```
After auth  I get this error. What's the problem?

**Comment by endoplasmic** [comment]
🤔, that looks like it couldn't detect the end of your request (or you kept talking for a long time). Is your mic input working ok?

**Comment by eouia** [comment]
I've tested arecord and aplay. both works well.
Anyway, after removing old token.js and getting new token, It works! I don't know why.

By the way, I have two questions.
1) When Assistant starts answering, some noise or distortion is burst at start of speech. So I cannot hear 0.x sec of begining of conversation. I doubt speaker needs some time gap for opening before output.
2) How to restart conversation? I want to converse again after 1-cycle question and answer are completed. how can I check Assistant ends? is there `assistant.on('ended')`? if so, can I put `assistant.start()` in there?

**Comment by eouia** [comment]
auch... 
The error returned. I didn't anything! And removing token doesn't fix this error again. This is a mystery.

**Comment by endoplasmic** [comment]
Yah I'm not super sure why you are having those problems to be honest.

1) What platform are you running this on? I've tried mac and windows and it's been fine for me.
2) close, here is what I do in the mic-speaker example: 
```js
conversation.on('ended', (error, continueConversation) => {
      if (error) console.log('Conversation Ended Error:', error);
      else if (continueConversation) assistant.start();
      else console.log('Conversation Complete');
});
```

**Comment by eouia** [comment]
Thanks. I'll close this.

**Comment by eouia** [comment]
Just for others who have same trouble with me;
This Audio_in too long error comes from lpcm16. change record program `rec` to `arecord`.
