### ISSUE TITLE
Wrong Example On npm Page

### ISSUE THREAD

**Issue by NoobTW** [endoplasmic/google-assistant#14]
The example on [npm page](https://www.npmjs.com/package/google-assistant) is wrong.

![image](https://user-images.githubusercontent.com/9292238/28919820-be1c3698-7881-11e7-88aa-f6b65ea082d4.png)
should be `() => `

BTW, the `README.MD` on GitHub is correct.

**Comment by endoplasmic** [comment]
Sorry for the late reply. Had to wait until I did some new stuff to up the version number before pushing to npm.

Should be good now :)
