### ISSUE TITLE
Write mp3 to Assistant

### ISSUE THREAD

**Issue by CTKRocks** [endoplasmic/google-assistant#15]
Is it possible to write mp3 data to the assistant?

**Comment by endoplasmic** [comment]
Do you mean having a pre-recorded MP3 with speech in it? Something like "Turn on the kitchen lights" as a recording that is triggered by another event.

Yah for sure!

You would just need to stream the byte output of the audio after starting a new conversation with the assistant. There are a few command line audio players and I gotta assume most of them allow you to pipe the output.

**Comment by CTKRocks** [comment]
Exactly. An mp3 file with speech pre-recorded that I would like to pipe into the assistant. I wasn't able to get it working, do you know how I could? Would it be as simple as:

```javascript
fs.readFile('file.mp3', function read(err, data) {
        if (err) {
            throw err;
        }
        console.log(data);
        // Send the data to the conversation
        conversation.write(data);
});
```

This is what I tried, but it didn't seem to work.

**Comment by CTKRocks** [comment]
Oops

**Comment by endoplasmic** [comment]
It wouldn't work like that because you're not playing the data back (you're just getting the bytes from the file). 

What you would need to use is something like SoX or ffmpeg to play the file and pipe it to the conversation.

**Comment by CTKRocks** [comment]
How would I do this with SoX? ffmpeg is mostly for videos I'm pretty sure. The node SoX package doesn't have much documentation.

**Comment by CTKRocks** [comment]
Looks like [this](https://github.com/ArtskydJ/sox-stream)(sox-stream) may work.

But I'm not sure how to pipe into the conversation.write command:

```javascript
var src = fs.createReadStream('file.mp3');
var soxStream = sox({ input: { volume: 1.0 }, output: { type: 'mp3' }});
src.pipe(soxStream).pipe(conversation.write?);
```

**Comment by CTKRocks** [comment]
Okay, so I assume I just `pipe(conversation)`, however the conversation doesn't get any data. I believe this stream is incorrect and is just piping the info to the file, not playing.

I'm not sure how to implement this..

**Comment by CTKRocks** [comment]
So I got closer, except now it says `{ Error: Invalid 'audio_in': too long.`
The audio file is 1 second long.. Here's my code:
```javascript
var stream = fs.createReadStream('file.mp3');
var decoder = new lame.Decoder();
stream.pipe(decoder).on('format', function(format) {
  this.pipe(conversation);
});
```

**Comment by CTKRocks** [comment]
Yes! I got it working! I piped it directly from the file download instead of `fs.createReadStream`

I hope this helps anyone who has this same issue!

**Comment by endoplasmic** [comment]
Let's take your final code chunk and turn it into an example if you're willing to share it. Not sure how many people read the issues :)

**Comment by CTKRocks** [comment]
Okay.

**Comment by CTKRocks** [comment]
Check #16
