### ISSUE TITLE
AssertionError: Failure: Type not convertible to Uint8Array

### ISSUE THREAD

**Issue by bighenry-lai** [endoplasmic/google-assistant#17]
anyone got the error when send audio data?

Say something!
Conversation Error: { [AssertionError: Failure: Type not convertible to Uint8Array.]
  message: 'Failure: Type not convertible to Uint8Array.',
  reportErrorToServer: true,
  messagePattern: 'Failure: Type not convertible to Uint8Array.' }
Conversation Error: { [Error: Serialization failure] code: 13, metadata: Metadata { _internal_repr: {} } }

**Comment by endoplasmic** [comment]
What kind of audio data are you trying to send? I've never seen that before

**Comment by bighenry-lai** [comment]
The returned sound data  of "node-record-lpcm16" is not uint8 data, so i solve this by convert the sound data to uin8 array, it's working now

**Comment by endoplasmic** [comment]
I mean node buffers are always uint8 arrays, so maybe your node version is a bit older? That's cool that you found something that works for you though!

**Comment by oroce** [comment]
@bighenry-lai see: https://github.com/endoplasmic/google-assistant/issues/21#issuecomment-326806870
