### ISSUE TITLE
Doesn't work when following README

### ISSUE THREAD

**Issue by snollygolly** [endoplasmic/google-assistant#19]
I'm trying to get up and running based on the instructions in the README, but I'm unable to.  When running the first sample, it waits for 5 seconds or so and then shows this:

```
Service unavailable.
{ Error: Unknown Error.
    at ClientDuplexStream._emitStatusIfDone (/Users/USER/Desktop/PROJECT/node_modules/grpc/src/node/src/client.js:270:19)
    at ClientDuplexStream._receiveStatus (/Users/USER/Desktop/PROJECT/node_modules/grpc/src/node/src/client.js:248:8)
    at /Users/USER/Desktop/PROJECT/node_modules/grpc/src/node/src/client.js:772:12
  code: 2,
  metadata: Metadata { _internal_repr: { 'content-disposition': [Object] } } }
```

Everything is entered exactly as is shown in the first example with the exception of the config which is as shown below:

```
const config = {
  auth: {
    keyFilePath: `${__dirname}/secret.json`,
    // where you want the tokens to be saved
    // will create the directory if not already there
    savedTokensPath: `${__dirname}/tokens/tokens.js`,
  }
};
```

I've tried the other demos as well, but I get the same error for both (console and mic):

```
Conversation Error: { AssertionError: Failure: Type not convertible to Uint8Array.
    at new goog.asserts.AssertionError (/Users/USER/Desktop/PROJECT/node_modules/google-protobuf/google-protobuf.js:98:603)
```

Thoughts?

**Comment by endoplasmic** [comment]
What do you get for `node -v` and `npm -v`?

**Comment by snollygolly** [comment]
Node: `v6.6.0`
NPM: `v3.10.3`

**Comment by asturel** [comment]
Same issue here :(
```
Service unavailable.
{ Error: Unknown Error.
    at ClientDuplexStream._emitStatusIfDone (/home/pi/node_modules/grpc/src/node/src/client.js:270:19)
    at ClientDuplexStream._receiveStatus (/home/pi/node_modules/grpc/src/node/src/client.js:248:8)
    at /home/pi/node_modules/grpc/src/node/src/client.js:772:12
  code: 2,
  metadata: Metadata { _internal_repr: { 'content-disposition': [Array] } } }
```
npm: 5.3.0
node: v8.4.0

**Comment by endoplasmic** [comment]
Hey hey,

I've made some changes based on this issue: https://github.com/endoplasmic/google-assistant/issues/21

Was hoping you could try again and see if things sort themselves out? (@asturel, I'm curious if my changes broke it on the pi or not)

**Comment by asturel** [comment]
mic-speaker example just works fine on rpi3 (raspbian), thanks! 
btw the grpc "doesnt support" hotword detection?

**Comment by endoplasmic** [comment]
@asturel you'd have to use something like [Snowboy](https://snowboy.kitt.ai/) to handle the wake word and then trigger the conversation to start.

@snollygolly did it work out ok for you now?

**Comment by asturel** [comment]
Sometimes I still get:

```
hotword 1 Ok Google
Say something!
Conversation Error: Service unavailable.
Conversation Error: { Error: Unknown Error.
    at ClientDuplexStream._emitStatusIfDone (/home/pi/node_modules/google-assistant/node_modules/grpc/src/node/src/client.js:201:19)
    at ClientDuplexStream._receiveStatus (/home/pi/node_modules/google-assistant/node_modules/grpc/src/node/src/client.js:180:8)
    at /home/pi/node_modules/google-assistant/node_modules/grpc/src/node/src/client.js:649:14
  code: 2,
  metadata: Metadata { _internal_repr: { 'content-disposition': [Array] } } }

```

**Comment by CloakedAlien** [comment]
Can confirm I'm also getting this issue.
Ubuntu 16.04 64bit
node 6.12
npm 3.10.10

Conversation Error: Service unavailable.
Conversation Error: { Error: Unknown Error.
    at ClientDuplexStream._emitStatusIfDone (/home/***/gatest/node_modules/grpc/src/node/src/client.js:201:19)
    at ClientDuplexStream._receiveStatus (/home/***/gatest/node_modules/grpc/src/node/src/client.js:180:8)
    at /home/***/gatest/node_modules/grpc/src/node/src/client.js:649:14
  code: 2,
  metadata: Metadata { _internal_repr: { 'content-disposition': [Object] } } }

**Comment by niravpatel2008** [comment]
I am also having same issue on raspberry pi 3.

**Comment by navanchauhan** [comment]
Issue : 
```
{ Error: Service unavailable.
    at ClientDuplexStream._emitStatusIfDone (/Users/navanchauhan/Coding and Stuff/node_modules/grpc/src/node/src/client.js:201:19)
    at ClientDuplexStream._receiveStatus (/Users/navanchauhan/Coding and Stuff/node_modules/grpc/src/node/src/client.js:180:8)
    at /Users/navanchauhan/Coding and Stuff/node_modules/grpc/src/node/src/client.js:649:14 code: 14, metadata: Metadata { _internal_repr: {} } }
```

**Comment by endoplasmic** [comment]
Hmm, looks like grpc is being a dummy.

I have it locked in the package file, but if you install the latest version (as a test), does it fix it?

**Comment by navanchauhan** [comment]
@endoplasmic Sorry, but I don't understand you, what should I do ? run `npm install google-assistant` again, install grpc via npm or clone the repo again ?

**Comment by endoplasmic** [comment]
My bad, i updated it to 1.8.0 in the package file. Try it again, if it doesn't work I'll have to dust off my pi 😁

**Comment by endoplasmic** [comment]
Alright, I dusted off the Pi and basically as long as you pass the right params to the mic, it all works great!

```js
const mic = record.start({ threshold: 0, recordProgram: 'arecord', device: 'plughw:1,0' });
```

The `plughw:1,0` is just a USB microphone.
```
$ arecord -l
**** List of CAPTURE Hardware Devices ****
card 1: U0x46d0x821 [USB Device 0x46d:0x821], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
``` 
card **1** device **0** is where the `plughw:CARD,DEVICE` gets filled in.

Basically you need to look into the `~/.asoundrc` file and have a valid configuration for your particular setup.

Hope that helps!
