### ISSUE TITLE
Running index.js

### ISSUE THREAD

**Issue by sharmmoh1983** [endoplasmic/google-assistant#2]
Paste your code: (node:7847) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Exited with code 3
(node:7847) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by endoplasmic** [comment]
Hmm, I'm not even using promises. Can you paste some of your code to see if we can't tell what's going on?

**Comment by sharmmoh1983** [comment]
I have handled this exception in the code and there is no error now
