### ISSUE TITLE
undefined symbol: SSL_CTX_set_alpn_protos

### ISSUE THREAD

**Issue by sipvoip** [endoplasmic/google-assistant#20]
[root@apu google-assistant]# node examples/mic-speaker.js 
Say something!
node: symbol lookup error: /root/google-assistant/node_modules/grpc/src/node/extension_binary/grpc_node.node: undefined symbol: SSL_CTX_set_alpn_protos

Any ideas? Running on Centos 7, looks like the issue may be with the stupid old openSSL they use.

**Comment by endoplasmic** [comment]
I honestly couldn't tell you at all. Only thing I can think of is to make sure you're running node 6.11 and npm 3.10.10?

**Comment by endoplasmic** [comment]
I made some tweaks to the package file to *not* use the latest `grpc` stuff. Can you give it a whirl again and see if it's sorted out?
