### ISSUE TITLE
Response data in MP3 format.

### ISSUE THREAD

**Issue by Mnark** [endoplasmic/google-assistant#22]
When setting the encodingOut to 'MP3', the response are still in raw format.

The problem appears to be @ lines 32 and 34 of conversation.js...

When validating the parameter, the function is iterating over embeddedAssistant.AudioInConfig.Encoding, I believe this should be embeddedAssistant.AudioOutConfig.Encoding.

Would you like a pull request?

**Comment by endoplasmic** [comment]
Thanks for the heads up. I made the changes and published under 0.1.13.
