### ISSUE TITLE
Probably doing something stupid

### ISSUE THREAD

**Issue by intotheweb101** [endoplasmic/google-assistant#23]
Hi, I am using the console-input example

I am getting the error 
> TypeError: Cannot read property 'client_id' of undefined

Here is my auth file

`{"key":
	{
		"client_id":"client_id",
		"project_id":"project_id",
		"auth_uri":"auth_uri",
		"token_uri":"token_uri",
		"auth_provider_x509_cert_url":"auth_provider_x509_cert_url",
		"client_secret":"client_secret"
	}
}`

here is the link to my config
const config = {
  auth: {
    keyFilePath: `${__dirname}/creds.json`,
    savedTokensPath: `${__dirname}/tokens/tokens.js`,
  },
  audio: {
    encodingIn: 'LINEAR16', // supported are LINEAR16 / FLAC (defaults to LINEAR16)
    sampleRateOut: 24000, // supported are 16000 / 24000 (defaults to 24000)
  },
};

Any help would be great

**Comment by endoplasmic** [comment]
Hmm, so my JSON looks a little bit different. Instead of "key", mine says "installed" (formatted so you can read it better):

```json
{  
   "installed":{  
      "client_id":"xxxxxxxxx",
      "project_id":"xxxxxxx",
      "auth_uri":"https://accounts.google.com/o/oauth2/auth",
      "token_uri":"https://accounts.google.com/o/oauth2/token",
      "auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs",
      "client_secret":"xxxxxxxxx",
      "redirect_uris":[  
         "urn:ietf:wg:oauth:2.0:oob",
         "http://localhost"
      ]
   }
}
```
