### ISSUE TITLE
Config issues

### ISSUE THREAD

**Issue by Nevexo** [endoplasmic/google-assistant#24]
Environment:
Node 8.8.0

Hey, I have the following config:
`const config = {
  auth: {
    keyFilePath: 'keys.json',
    savedTokensPath: 'tokens.js', // where you want the tokens to be saved
  },  
  audio: {
    encodingIn: 'LINEAR16', // supported are LINEAR16 / FLAC (defaults to LINEAR16)
    sampleRateOut: 24000, // supported are 16000 / 24000 (defaults to 24000)
  },
};`
But when spinning up the GoogleAssistant it spits out:
`Error: Cannot find module 'keys.json'
`
Like it's loading the file like a module. Just in case it's being required I tried ./keys.json and the same thing happened, either I'm being stupid or something has changed in Node 8

**Comment by endoplasmic** [comment]
Does it work if you use 6.11? I haven't gone down the 8 road yet.

**Comment by Nevexo** [comment]
I'll give it a try in a minute

**Comment by endoplasmic** [comment]
I just pushed changes for v1alpha2 and I'm on node 8.9.4 and things worked just fine. Going to close this!
