### ISSUE TITLE
Response as text

### ISSUE THREAD

**Issue by koenhendriks** [endoplasmic/google-assistant#25]
Is there anyway to get the response of the assistant as text / string? 

As a workaround i could  use a speech to text api but i'd rather not.

**Comment by endoplasmic** [comment]
The only way that I know of is using IFTTT. I don't use it myself, but that's basically the only way (as of now) to get a transcription of what the assistant said :(

**Comment by endoplasmic** [comment]
With v1alpha2 they now allow us to send text natively! Grab 0.2.0 and you should be good to go. For an example of sending / receiving text, check out the console-input example: https://github.com/endoplasmic/google-assistant/blob/master/examples/console-input.js
