### ISSUE TITLE
Give me permission to help you?

### ISSUE THREAD

**Issue by alvaro1728** [endoplasmic/google-assistant#29]
I'm trying to run the console-input example since I'm only interested in text-based communications.  I set everything up as instructed, downloaded the OAuth JSON file, and ran it.  I get this:

```
Type your request: Who won the Superbowl last year?
Fetching TTS file...
Transcription: who won the Superbowl last year
Assistant Speaking
Conversation Complete
Assistant Finished Speaking
```

So I hear a lady's voice saying "Give me permission to help you". What am I missing?

Thanks,
Alvaro

**Comment by endoplasmic** [comment]
If you want to hold tight a little bit, the new APIs actually support text input so we won't have to do this hack anymore.

I'll update this issue once I get it all hooked up :)

**Comment by endoplasmic** [comment]
Alright, I've completely changed the console example since the new APIs support the ability to send text to the assistant. Go ahead and update and let me know if you hit any issues.
