### ISSUE TITLE
Running 

### ISSUE THREAD

**Issue by sharmmoh1983** [endoplasmic/google-assistant#3]
Error getting tokens: { Error: getaddrinfo ENOTFOUND accounts.google.com accounts.google.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'accounts.google.com',
  host: 'accounts.google.com',
  port: 443 }

**Comment by endoplasmic** [comment]
In your web browser, what happens when you go to https://accounts.google.com ??

**Comment by sharmmoh1983** [comment]
This is working now.  I am getting tokens in file

But nothing happens when control goes to conversation.js . getting error

**Comment by sharmmoh1983** [comment]
I am running the code on raspberry pi. Is this a working code ?

**Comment by endoplasmic** [comment]
I wanted to test on my Raspberry Pi 3 as well (I'm actually typing this comment from it!). 

Everything installed for me just fine and I was able to run the `mic-speaker.js` file after installing the mic and speaker dependencies.

I don't have any other Pi's around, so I can't comment on if it works on them or not.

FWIW, I'm running node 6.10.3 if that helps you debug.

**Comment by sharmmoh1983** [comment]
I am also using Raspberry Pi 3. I am ble to run one index file I have created but it seems to give some eeror from conversations.js . I will share the error and the file i am using soon

**Comment by sharmmoh1983** [comment]
This is the following error i m getting:
pi@raspberrypi:~ $ node index.js
(node:1158) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
conversation is on
events.js:168
      throw err;
      ^

Error: Uncaught, unspecified "error" event. (14,Service unavailable.,)
    at Conversation.emit (events.js:166:17)
    at ClientDuplexStream.Conversation.conversation.on (/home/pi/node_modules/google-assistant/components/conversation.js:113:12)
    at emitOne (events.js:96:13)
    at ClientDuplexStream.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at ClientDuplexStream.Readable.push (_stream_readable.js:136:10)
    at readCallback (/home/pi/node_modules/google-assistant/node_modules/grpc/src/node/src/client.js:245:14)



------------------------

Following is the content in index.js


const GoogleAssistant = require('google-assistant');
const config = {
  auth: {
    keyFilePath: '/home/pi/client_secret_449743712391-aljimmkvn5ojr1i3mhi5ej8km$
    savedTokensPath: '/home/pi/tokens.js', // where you want the tokens to be s$
  },
};
const assistant = new GoogleAssistant(config);

// will start a conversation and wait for audio data
assistant.on('ready', () => assistant.start())

**Comment by endoplasmic** [comment]
[Alright, so basically the problem was that my README just didn't give enough base info for you to get up and running. 

The `Usage` section is really just a bare bones way to instantiate it and start a conversation.

You can head back to the main page of this repo to see the updated README now (fixed in commit: https://github.com/endoplasmic/google-assistant/commit/25a7c7d58cae6dfd228d26873b27db89041e5233)

**Comment by sharmmoh1983** [comment]
pi@raspberrypi:~ $ node  index.js
(node:827) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
conversation is on
{ wrappers_: null,
  messageId_: undefined,
  arrayIndexOffset_: -1,
  array: [ 14, 'Service unavailable.', [] ],
  pivot_: 1.7976931348623157e+308,
  convertedFloatingPointFields_: {} }
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: Unknown Error.
    at ClientDuplexStream._emitStatusIfDone (/home/pi/node_modules/google-assistant/node_modules/grpc/src/node/src/client.js:201:19)
    at ClientDuplexStream._receiveStatus (/home/pi/node_modules/google-assistant/node_modules/grpc/src/node/src/client.js:180:8)
    at /home/pi/node_modules/google-assistant/node_modules/grpc/src/node/src/client.js:649:14

**Comment by endoplasmic** [comment]
You're not listening for the error event. 

Please check out the mic-speaker.js file in the examples folder.
