### ISSUE TITLE
Streaming music or radio

### ISSUE THREAD

**Issue by dolanmiu** [endoplasmic/google-assistant#31]
Would this library work with indefinite streamed audio such as music, or the radio?

Thanks!

**Comment by endoplasmic** [comment]
Not yet :(

**Comment by dolanmiu** [comment]
Turns out that the python library also doesn't support it:

https://github.com/googlesamples/assistant-sdk-python/issues/161#issuecomment-356816857

**Comment by greghesp** [comment]
Is it possible to pass an audio file to this?
For example, if I stitched together audio of the word "Broadcast" followed by a doorbell sound.

That way, it would broadcast "ding dong" to my Google Homes

**Comment by endoplasmic** [comment]
That is an amazing idea. Whenever they fix broadcasting from the sdk, that would totally work. (you would hear the broadcasting tone first though, but otherwise you should be good)

**Comment by greghesp** [comment]
I was trying to figure out how to do this previously, however my experience with Buffers and Audio is zero, so it went right over my head.

I already made a sample file:
https://github.com/greghesp/assistant-relay/blob/master/audio/bell.wav

**Comment by greghesp** [comment]
@endoplasmic since Google has fixed broadcasting, how do you see this working? I've been trying to figure out how to pass it an audio file rather than stream from a mic but can't get my head around it.

**Comment by greghesp** [comment]
@endoplasmic  I still haven't managed to get this working

This is what I am trying:

```
    var file = fs.createReadStream(`${path.resolve(__dirname, 'response.wav')}`);
    assistant.start(global.config.conversation, (conversation) => {
      conversation.write(file)
       return self.startConversation(conversation)
       .then((data) => {
         console.log(data)
       })
       .catch((err) => {
         console.log(err)
       })
     });
```

but it throws:

> { AssertionError: Failure: Type not convertible to Uint8Array.
>     at new goog.asserts.AssertionError (C:\Users\greg_\Documents\Node\assistant-relay\node_modules\google-protobuf\google-protobuf.js:105:603)
>     at Object.goog.asserts.fail (C:\Users\greg_\Documents\Node\assistant-relay\node_modules\google-protobuf\google-protobuf.js:107:89)
>     at Object.jspb.utils.byteSourceToUint8Array (C:\Users\greg_\Documents\Node\assistant-relay\node_modules\google-protobuf\google-protobuf.js:254:281)
>     at jspb.BinaryWriter.writeBytes (C:\Users\greg_\Documents\Node\assistant-relay\node_modules\google-protobuf\google-protobuf.js:292:83)
>     at Function.proto.google.assistant.embedded.v1alpha2.AssistRequest.serializeBinaryToWriter (C:\Users\greg_\Documents\Node\assistant-relay\node_modules\google-assistant\lib\google\assistant\embedded\v1alpha2\embedded_assistant_pb.js:1576:12)
>     at proto.google.assistant.embedded.v1alpha2.AssistRequest.serializeBinary (C:\Users\greg_\Documents\Node\assistant-relay\node_modules\google-assistant\lib\google\assistant\embedded\v1alpha2\embedded_assistant_pb.js:1553:58)
>     at requestSerialize (C:\Users\greg_\Documents\Node\assistant-relay\node_modules\google-assistant\components\embedded-assistant.js:10:27)
>     at ClientDuplexStream.serialize (C:\Users\greg_\Documents\Node\assistant-relay\node_modules\grpc\src\common.js:38:12)
>     at ClientDuplexStream._write (C:\Users\greg_\Documents\Node\assistant-relay\node_modules\grpc\src\client.js:143:20)
>     at doWrite (_stream_writable.js:406:12)
>      message: 'Failure: Type not convertible to Uint8Array.',
>      reportErrorToServer: true,
>      messagePattern: 'Failure: Type not convertible to Uint8Array.' }

Any ideas?

**Comment by endoplasmic** [comment]
I know this is a bit old, but a) is this working yet, and b) could you fire me over your WAV file if it isn't?
