### ISSUE TITLE
Multiple Google Accounts

### ISSUE THREAD

**Issue by greghesp** [endoplasmic/google-assistant#33]
Is it possible to use multiple Google accounts by supporting multiple client files and tokens?

**Comment by endoplasmic** [comment]
I don't see why not, you just have 2 different config objects and create 2 instances of the assistant.

```js
const config: {
  auth1: { keyFilePath: xxxx, savedTokensPath: xxxx },
  auth2: { keyFilePath: yyyy, savedTokensPath: yyyy },
};

const assistant1 = new GoogleAssistant(config.auth1);
const assistant2 = new GoogleAssistant(config.auth2);
```

**Comment by greghesp** [comment]
Oh wow, I never even thought about doing it like that. Thanks!

**Comment by greghesp** [comment]
Trying to get this to work now, however running into an issue when adding the auth codes. 
My code loops through the config, opens the windows, but there is no pause to wait on entering the code into the terminal, so you can only ever enter the last users code:

`const authKeys = GRConfig.users;
let assistants = {}

const config = {
  conversation: {
    lang: GRConfig.language,
  },
  users:{}
}

Object.keys(authKeys).forEach(function(k) {
  config.users[`${k}`] = {};
  config.users[`${k}`].keyFilePath = path.resolve(__dirname, authKeys[k]);
  config.users[`${k}`].savedTokensPath = path.resolve(__dirname,`${k}-tokens.json`);
})

var usersX = config.users;

Object.keys(usersX).forEach(function (k) {
  assistants[`${k}`] = new GoogleAssistant(config.users[`${k}`]);
})`
