### ISSUE TITLE
Windows availability for console input only?

### ISSUE THREAD

**Issue by greghesp** [endoplasmic/google-assistant#34]
The project I'm working on only requires the console input function, and not the mic/speaker setup.

As it is now, I dont believe this can run on Windows due to the mic/speaker config. Is it possible to strip out all the mic/speaker stuff and just have the console commands only to run on windows?

**Comment by navanchauhan** [comment]
Yes, It's quote possible

**Comment by navanchauhan** [comment]
Just tweak the console-input file according to your need

**Comment by greghesp** [comment]
I've already done that, but this lib wont work on Windows due to the dependencies on some audio stuff (i think) that only works on unix

**Comment by endoplasmic** [comment]
Can you post your console output? This works on Windows, so you must have
something up with your config.

**Comment by endoplasmic** [comment]
![image](https://user-images.githubusercontent.com/118301/34910031-fe6b5a7a-f861-11e7-9382-a3bd430dc3b3.png)

Screenshot for proof :)

**Comment by navanchauhan** [comment]
@greghesp Could you post the error code

**Comment by greghesp** [comment]
Closed.  No idea why it wasn't originally working for me but seems fine now
