### ISSUE TITLE
Empty response returned in console-input.js example

### ISSUE THREAD

**Issue by matueranet** [endoplasmic/google-assistant#36]
Hi,

First, thanks for this brilliant module. I am using it to create a plugin for https://github.com/matueranet/genie-router. I succesfully authenticated and created a token. After that, in my plugin code the Assistant response only returned an empty string. So I attempted to run your cli-input.js example to see if that worked. 

There the returned Assistant was also empty, see output:
```
Type your request: hello
Assistant Response: 
Conversation Complete
```

Any idea what's going on here?

**Comment by endoplasmic** [comment]
Sadly this text isn't a 1:1 transcription of what the assistant is saying. If she did say something, then it sounds like a bug on Google's end sadly.

**Comment by matueranet** [comment]
Thanks for the reply, that is unfortunate. It also responds with an empty reply if I ask for actual information, such as the time. Is there a way for me to see the raw data that was returned by the Google servers?

**Comment by endoplasmic** [comment]
Hmm, I'm seeing the text in the replies I my end...

```
Type your request: hello
Assistant Response: What can I do for you?
Type your request: nothing right now
Assistant Response: No problem
Conversation Complete
```

```
Type your request: what time is it?
Assistant Response: The time is 9:45 PM.
Conversation Complete
```

**Comment by matueranet** [comment]
Thanks for checking! As it turns out, the Google account I used to authenticate with was a Google Apps account, on which access to the Assistant was not enabled. Apparently that does not trigger an error, but results in empty responses. Using a different (normal gmail) account I was able to get the example working.

**Comment by endoplasmic** [comment]
Good to know about that actually. I'm sure this thread will help others as well!

**Comment by Baael** [comment]
For me it wasn't solution. I solved it with 

> in Activity Controls page, make sure to taggle "Include Chrome browsing history and activity from websites and apps that use Google services"

https://stackoverflow.com/questions/46482807/google-assistant-sdk-returns-give-me-the-permission-to-help-you
