### ISSUE TITLE
Manually handle oauth page open?

### ISSUE THREAD

**Issue by FezVrasta** [endoplasmic/google-assistant#37]
I'm writing an Electron app and I'd like to let my users authorize Google Assistant from within my app, right now this package will automatically open a browser window, but I'd like instead to show the auth window in an in-app page.

Also, I'd then need a way for the user to paste the token in some UI of my app and forward it to this package.

How can I do?

**Comment by endoplasmic** [comment]
Check out: https://github.com/WMisiedjan/electron-google-oauth

**Comment by FezVrasta** [comment]
Thanks, but what I don't get is how to override the built-in authentication step then...

**Comment by endoplasmic** [comment]
I haven't needed to do that sort of thing yet, so I haven't looked into his code, but basically that's what his stuff does.

Download it and try!

**Comment by FezVrasta** [comment]
I think I didn't express myself clearly, I know how to authenticate to Google using that library, I don't know how to tell your library to use the authentication provided by `electron-google-oauth`

**Comment by endoplasmic** [comment]
Ahhh, I think in this situation it might be an either/or.

I'd have to dig to see what type of key it'd need in order to work the way you want. At the moment this version doesn't support that style of auth. :(

**Comment by FezVrasta** [comment]
Ok thanks anyway

**Comment by WMisiedjan** [comment]
@endoplasmic Thanks for referencing my project!

@FezVrasta What the Google Assistant Desktop Client basically is doing is that it is opening the authentication page from Google in a new, borderless window. Google puts the authentication key in the page title once the user has succesfully authenticated, the electron-google-oauth plugin reads that title and gives it back as a Promise. 

It should be that hard to integrate within this library too! Let me know what you're stuck at, I might be able to help.

**Comment by endoplasmic** [comment]
Right on @WMisiedjan! You're in good hands @FezVrasta, this guy does great work :)

**Comment by FezVrasta** [comment]
I'm quite sure work must be done on this library to allow 3rd party integration.

**Comment by E3V3A** [comment]
@WMisiedjan @endoplasmic 
Hi Guys! Any updates on this? 
This could be a very important workaround to the unhandledPromise Rjection caused in the `opn`.
The code [here](https://github.com/endoplasmic/google-assistant/blob/master/components/auth.js#L46-L48), doesn't seem to handle anything. According to the errors I get, we are dealing with an unhandled promise, so probably you need to put some `try/catch` around that code? 

```js
    // open the URL
    opn(url);
console.log('Attempted to automatically open the URL, but if it failed, copy/paste this in your browser:\n', url);
```

Otherwise [we get these](https://github.com/eouia/MMM-Assistant/issues/28) kind of errors.

**Comment by endoplasmic** [comment]
Alright, I fixed the Promise thing in https://github.com/endoplasmic/google-assistant/commit/7f56fbc6bc6ccd7e906c963e47fa763a7c8fbd42

As far as your other issue, if you want to use this library without doing the browser auth part, you would need to do that at some point and just save the .json file someplace. You could then reference that file in your `config.auth.savedTokensPath` and it'll skip the auth step and just read that file.

Hope that helps!
