### ISSUE TITLE
Auth problem.

### ISSUE THREAD

**Issue by eouia** [endoplasmic/google-assistant#4]
Hi.
I'm testing your code in my OSX laptop.
After finishing install (including node-record-lpcm, node-speaker), I tried to test your mic-speaker.js
I created and downloaded client_secret_xxx_json for auth.
````JS
[mic-speaker.js]
const config = {
  auth: {
    keyFilePath: './client_secret_xxxxxxx....apps.googleusercontent.com.json',
    savedTokensPath: './tokens.js', // where you want the tokens to be saved
  },
````
Is this right?
But when I try to run this. (node mic-speaker.js), I meet this error code.
````
module.js:471
    throw err;
    ^

Error: Cannot find module './client_secret_xxxxxxx.....apps.googleusercontent.com.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at new Auth (..../google-assistant/components/auth.js:27:15)
    at new GoogleAssistant (..../google-assistant/index.js:16:16)
    at Object.<anonymous> (..../google-assistant/examples/mic-speaker.js:76:19)
...
````
I guess this error indicates me something wrong I've done. Does keyFilePath mean some kind of JS file? not js? But I cannot find any instruction for this kind of file. Can you tell me more details?

**Comment by endoplasmic** [comment]
Looks like you have the correct JSON file, but I'm guessing it's just not able to resolve where they are. If you didn't drop it in the `examples` directory, it won't be able to find it.

Try using a full path like `/Users/yourusernamehere/xxxxxxxx` and see if that helps (or you can use the `path` module to resolve the relative path)

**Comment by eouia** [comment]
it works. thanks
