### ISSUE TITLE
Hotword to start conversation

### ISSUE THREAD

**Issue by henryoliver** [endoplasmic/google-assistant#40]
Hey guys, how can I implement some initial trigger on the `mic-speaker.js` example? I can run it without end the conversation by using `pm2` but I would like to implement a `hotword` to start the conversation. Any snippet or example will help a lot. Thanks!

**Comment by endoplasmic** [comment]
This should get you started: https://snowboy.kitt.ai

I will say though that it requires a *ton* of tweaking to make it not trigger on it's own.

**Comment by henryoliver** [comment]
I'm looking through the `https://github.com/evancohen/sonus` documentation.

**Comment by endoplasmic** [comment]
The problem with that approach is that you would be starting/stopping a lot and processing everything the mic hears.

Once you get the text results, then you'd need to look through the text and find the wake word. Once you found it, you'd need to stop sending the audio for speech to text and instead send it for the assistant.

This is why wake word software is a thing :)

**Comment by henryoliver** [comment]
@endoplasmic it does make sense. Last question: `snowboy` is the only offline/software library that supports nodejs integration? Any other nodejs offline/noapi hotword solution you aware of?

Thank you again for your help!
