### ISSUE TITLE
How to "save" the audio-data?

### ISSUE THREAD

**Issue by atsushidev** [endoplasmic/google-assistant#43]
Hello, I'm actually using this **beautiful** module. 
Actually, I'm using it for a personal project. 

So, I want to get the audio bytes from ``audio-data`` event and stream it as a ``ReadableStream``.
I'm very new at NodeJS streams so if someone can help me 😄 

And if someone can tell me **how to convert a PCM stream to a proper Google format** because I'm getting "Service Unavailbale" errors (seen [here](https://github.com/endoplasmic/google-assistant/issues/26#issuecomment-361803297)).

Thank you very much for reading!

**Comment by motorvor** [comment]
I just left a comment on #57, but I'm having the same issue as well. Can't seem to figure out what would be causing this.
