### ISSUE TITLE
Client JSON Process broken

### ISSUE THREAD

**Issue by greghesp** [endoplasmic/google-assistant#45]
Does anyone have an alternative way to get the client json file from Google?  
It seems they've changed their sign up process and things are a little bit different now..

**Comment by endoplasmic** [comment]
Hmm, looks the same to me:

![image](https://user-images.githubusercontent.com/118301/39284329-8ab8ad74-48c7-11e8-8b0d-5ac1f95759a5.png)

OAuth:
![image](https://user-images.githubusercontent.com/118301/39284369-be3ba034-48c7-11e8-9863-8a7b6806d569.png)

**Comment by greghesp** [comment]
How did you get to that page? When I follow their new instructions, it talks about setting up device actions etc

**Comment by endoplasmic** [comment]
I link to it from the README, but here ya go: https://developers.google.com/assistant/sdk/guides/service/python/embed/config-dev-project-and-account

Then click the "ENABLE API" blue button
