### ISSUE TITLE
protobuf not working correctly

### ISSUE THREAD

**Issue by hufftheweevil** [endoplasmic/google-assistant#46]
I recently updated to v0.4.1 and I'm getting an error upon loading:

`Error: ENOENT: no such file or directory, open '[path-to-my-projects-folder]\lib\google\assistant\embedded\v1alpha2\embedded_assistant.proto'`

It appears that protobuf and/or proto-loader aren't resolving the path correctly. I don't know anything about protobuf, but I'm just making an observation. 

The actual path should be `[path-to-my-projects-folder]\[project-folder]\node_modules\google-assistant\lib\google\assistant\embedded\v1alpha2\embedded_assistant.proto`

Anyone with any hint as to how to fix this? Is it just me?

P.S. It was working before I updated.

**Comment by hufftheweevil** [comment]
I've fixed it, but I'm still not sure why this is a problem only for me. The change I made to my fork was in `components/proto-loader.js`. In line 7, I changed `../lib` to `node_modules/google-assistant/lib`

**Comment by endoplasmic** [comment]
I wasn't able to reproduce it initially, but wiped everything out and started fresh and had it happen. I checked in a fix that worked for me, but curious if it worked out for you as well: https://github.com/endoplasmic/google-assistant/commit/2351d08e77ab6f1d3a389e1e8e59176959f037e4

I also added the new ScreenOut stuff as well to play around with :)

**Comment by hufftheweevil** [comment]
Yup, that did it! Thanks for looking into it. And very nice project, btw.
