### ISSUE TITLE
grpc update due to lodash fix

### ISSUE THREAD

**Issue by hufftheweevil** [endoplasmic/google-assistant#47]
There was a recent update to grpc to address a lodash vulnerability, as seen in this commit:
https://github.com/grpc/grpc-node/commit/e97264c2d05080fb7d45e946fa47e48127afba73

I don't quite understand how the version numbers work when there are, what appears to be, multiple packages inside one package, like in grpc. I'm not sure what to do/recommend to update google-assistant to use the new version of grpc. Any help would be appreciated.

**Comment by endoplasmic** [comment]
I keep checking https://www.npmjs.com/package/protobufjs to see if there is an update, but nada.

```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ moderate      │ Denial of Service                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ protobufjs                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ grpc                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ grpc > protobufjs                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/605                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

I assume this is what you're talking about, ya?

**Comment by hufftheweevil** [comment]
gRPC v1.12.1 was published to npm.

**Comment by endoplasmic** [comment]
Hmm, they still have the old protobufjs in the package file:

![image](https://user-images.githubusercontent.com/118301/40464642-2ff1fbdc-5ed1-11e8-83c4-9fa2322d4625.png)

Published the latest in: https://github.com/endoplasmic/google-assistant/commit/57effeaa798720e73f61faa6cc6c3ab9a6283dc0
