### ISSUE TITLE
Set temperature unit possible ?

### ISSUE THREAD

**Issue by yorkching** [endoplasmic/google-assistant#49]
Is it possible to set the temperature unit (F/C) of the weather ? 
When asking the question like "What is the weather now", the result default would be given in Fahrenheit degree.

**Comment by WMisiedjan** [comment]
You can simply ask the assistant to change the tempature unit: 'Change the temperature unit to Fahrenheit (or Celcius)', I'm pretty sure you can also do this within the google assistant app on your phone, make sure you're logged into the same account on both devices.

**Comment by endoplasmic** [comment]
Yup, 2 options would be what @WMisiedjan said and the other (if you don't want it to be permanent) is to just say "What's that in celsius?"

**Comment by yorkching** [comment]
Thank you. it worked now.
