### ISSUE TITLE
Text broadcast command no longer working

### ISSUE THREAD

**Issue by greghesp** [endoplasmic/google-assistant#52]
I can't figure out of this is an issue related to this lib or if it's on Google's side.

I've been using this to send text commands to the service by sending 'broadcast hello world'

This recently stopped working and it seems to coincide with the SDK update.

Is anyone else having this issue?

**Comment by josharmour** [comment]
It looks like there is an official module here: https://www.npmjs.com/package/google-assistant-node

**Comment by endoplasmic** [comment]
oh @greghesp, they actually added support for sending text queries now. Just add `textQuery` to the conversation object and you'll be good to go.

You can also check out the console-input example.

**Comment by ryancasler** [comment]
I believe he already does.  This is in the conversation function:
config.conversation.textQuery = text;

**Comment by greghesp** [comment]
Ryan is correct, I set the textQuery parameter already. It seems to work for some stuff, but not the broadcast command.

Can't figure out if this is about undocumented Google 'feature' or if something else has changed

https://github.com/greghesp/assistant-relay/blob/master/index.js

**Comment by endoplasmic** [comment]
Yah, I see what you mean. The broadcast functionality has changed since now it actually streams your voice to all the google homes in your home, before you could send text using the assistant's voice.

It also looks like you can't broadcast from the SDK, so maybe they will re-add that back in :\

**Comment by greghesp** [comment]
Argh that's infuriating. Assistant has always streamed voice since that's how I use it normally.

Also annoying as the actual assistant still broadcasts text.

**Comment by josharmour** [comment]
@greghesp this is being fixed.  Hang tight.

**Comment by josharmour** [comment]
Ok, can you verify that it is working again @greghesp ?

**Comment by cogneato** [comment]
@greghesp @josharmour  same here. Assistant on phone now works again, SDK does not.

**Comment by greghesp** [comment]
@josharmour  is there a public issue tracker for this or an ETA?

**Comment by josharmour** [comment]
Unfortunately not.  I'm tracking this internally, and will ask the
developers to update soon.

**Comment by josharmour** [comment]
The ability for devices to broadcast to a group poses privacy risks (is the
broadcasting device a device that should be able to broadcast to the
devices on this network).  The key privacy risk was that broadcast from
Assistant SDK device would target linked devices outside this network
without the user's awareness.  A recent update limited the ability for
devices to broadcast in an effort to protect against this risk.  There is a
current proposal that is being tested that would re-enable this use case
but protect against the risk I mentioned earlier.

**Comment by greghesp** [comment]
That makes little sense. Unless someone has gained access to my account, explicitly created a project, enabled the API and downloaded my credentials then that can't happen.

Sure, I could share my token and secret with people which would give them access, but that applies for anything

By that logic, anything accessed via the SDK is a security risk.

**Comment by namdoh** [comment]
Hi Greg, I'm the eng lead of this feature on Assistant team. First of all, I'm sorry for disabling the feature without prior notifications or announcements to the dev community.

When user issues initiating a broadcast command from a static device (vs. mobile device like phone), they have two separate implicit intentions--broadcast to **all** linked devices or to just devices within the same network. For majority of users who have all their smart speaker devices in the same network, there are no difference. However, for a smaller group of users who have devices at multiple locations (e.g. at work and at home, or at multiple houses), it matters. And since we don't know for sure what the user wants, we err on the side of caution and broadcast from a static device only target devices in the same structure.

This brings us to the privacy concern issue.  Since we can't identify which devices are in the same network if broadcast initiating from an Assistant SDK device with the current design, we concern that a user may unknowingly broadcast a message intended for home circulation, and it ended up also broadcast to an office's device.

(Thank to Josh for bringing this issue to our attention and becoming a volunteered liaison for our team!)

**Comment by endoplasmic** [comment]
Hey @namdoh,

Appreciate you chiming in. I was thinking about your scenario and I feel it could be resolved a couple of ways and still bring back the existing functionality.

If you only have 1 location, then restoring functionality as it was seems pretty straight forward.

Multiple locations could ask for clarity, or allow it to be included as part of the message (in this case "the house"):

_"**broadcast to** the house dinner is ready"
"**broadcast** dinner is ready **to** the house"_

or

_you: "broadcast dinner is ready"
assistant: "Where did you want to broadcast that?"
you: "the house"_

That way if you are broadcasting from the SDK you need to be explicit as there where you want the message to go.

**Comment by greghesp** [comment]
Hey @namdoh,

Thanks for taking the time to come and comment!

That actually makes a lot of sense. I hadn't thought above that scenario and I can see how my relay used in conjunction with a smart home service could cause some problems there.

The most obvious solution from a user's points if view personally would be to use the group feature that already exists for casting audio.

Rather than do it based on location, could you not combine @endoplasmic suggestion with this?
That way you'd also kill 2 birds with 1 stone giving prop the ability to broadcast to selected devices.

Another suggestion is one you guys probably never hear the end of, and that's support for instant audio notifications, but that's probably a different situation all together.

Appreciate it's probably not that simple engineering wise, but it'd be great to get the functionality back.

**Comment by ryancasler** [comment]
Or you could just take the much simpler approach for now, while implementing a more robust fix in the future.
If all broadcasts from the assistant SDK went to all linked devices and that was made exicit to the user, then they would know how it work.  That way, the majority of us who fit into that one location bucket anyways, will get the functionalith back we need.  This would also take the pressure off for coming up with a quick and dirty fix and you can take the time to fix it the best way possible without pressure (at least from this angle) to finish it faster.  

Just an idea.  I'm just glad it's being addressed at all!

**Comment by greghesp** [comment]
@ryancasler if I understand it, thats actually the issue.
You never link a device, you give the SDK access to your account, not specific devices.

If you buy 5 Chromecasts for your business, load them to your account and then do the same for home, everyone at work will hear your broadcasts

**Comment by ryancasler** [comment]
I understand that.  But as long as people know that's the limitation, I don't see the issue.  Obviously fix it for the long term but just warn against it for now.

**Comment by jpoeppelman1** [comment]
I live in an area that has dangerous weather including many tornadoes.  Prior to this change I was able to receive tornado warnings through all of my google homes via SmartThings.  Personally I do not see how this is a security vulnerability knowing all devices are connected to the account and not location.  Please re-enable this feature as this change is putting my family at risk.  PLEASE GOOGLE!  Thank you!

**Comment by mhofman** [comment]
I also agree that for now, users should be made aware that linking an assistant device to their account will cause them to become broadcast targets.
After all, when using a mobile device, won't the broadcast be sent to all linked Google home devices?

I also support the idea of being able to create groups of home devices to be able to target a subset of devices. This could be orthogonal to the multiple location support so that a group may contain a few devices within a structure or devices spanning multiple structures.

**Comment by kebel87** [comment]
I'd like to +1 @greghesp suggestion. Being able to specify which group to broadcast to would be very useful and make perfect sense.

My use case is having 2 GHmini on each floor in the same house. I want to broadcast to both mini in the basement without waking up my daughter on the 2nd floor.

**Comment by frakman1** [comment]
Come on @namdoh . Surely this isn't beyond the wit of Google. Just default to to the same network and then add support for multiple locations later using a different API or any of the fine suggestions above.
You're breaking people's finely tuned home-automation setups.

**Comment by sbucaille** [comment]
Hi guys,

My disappointment level has reached its maximum. I just woke up with the brilliant idea to use Broadcasts to throw messages to my Home from my Smart Home project. It's currently 04:29 here, and after setting every thing up, the broadcast command doesn't work, I come to this thread, and I see that Google disabled the feature ! 😭 Well, I think I'll just go back sleeping and wait for the feature to come back 😂 
Let us know when it's back !

**Comment by greghesp** [comment]
Awesome news @namdoh.

Assuming it'd be more of a backend change rather than a user interaction one?
If you can't say, I'll wait and see before updating any of my code

**Comment by naseemr** [comment]
hoping this fix comes tomorrow.

**Comment by namdoh** [comment]
Hi @naseemr, ETA for the fix to take effect is next Friday.

**Comment by namdoh** [comment]
Hi guys, I just want to give a quick update. The fix was submitted, and unfortunately we had to roll it back later since it caused other issues. New ETA is next Friday.

Sorry for the inconveniences!

**Comment by do1eh** [comment]
Hi namdoh,
will the fix be rolled out worldwide or just US? Just asking because many features are not available here in germany even when they are not language dependend which is very annoying (e.g. music alarm).

**Comment by esalomo** [comment]
Hey guys, does anyone experience any issues in the past 2 days with broadcasting to grouped GH Devices?
I have all my devices (7 GHs) setup as homegroup but the broadcast to this group stopped working in the past 2 days

**Comment by fenixtxrbf** [comment]
Started working about an hour ago all on it's own. Very happy to have it back. Thanks everyone

**Comment by esalomo** [comment]
Same here , started working few minutes ago :)

**Comment by drjared88** [comment]
@namdoh Is this limited to just the US? It seems like in Canada, even though my Google Home is set to US English, this still doesn't work...

**Comment by JumpMaster** [comment]
It's working well in the UK. Language set to English UK.

**Comment by rummyr** [comment]
Working in UK too.

**Comment by esalomo** [comment]
one thing to note is that I had to remove and recreate my homegroup for the homegroup to work again.

**Comment by greghesp** [comment]
Issue has now been resolved.

Thanks @josharmour and @namdoh for getting this resolved

**Comment by jpoeppelman1** [comment]
Namdoh,

It appears the broadcast function is now working.  Has there been any
enhancements to target specific rooms/devices using broadcast?

Thanks
James

**Comment by mhofman** [comment]
@josharmour @namdoh, was anything changed again in the last couple days? The My Activity dashboard says messages are getting broadcast, but nothing plays out of the speakers.

**Comment by Laupet** [comment]
Same issue here

**Comment by josharmour** [comment]
It works for me.  I had to restart the assistant relay server like below:


User specified was josh
^C


pi@raspberrypi:~/assistant-relay $ npm run start

> assistant-relay@1.0.1 start /home/pi/assistant-relay
> node index.js

Firing up the Web Server for communication on address 192.168.86.248:3000
Assistant Relay is now setup and running for josh
Received command broadcast Assistant Relay is now setup and running for josh
No user specified, using josh
Received command broadcast "Back door is open"
User specified was josh
Received command broadcast "Back door is closed"
User specified was josh

**Comment by mhofman** [comment]
Indeed, it's working with `assistant-relay`. I was actually testing with an equivalent project in python, that no longer works.

**Comment by do1eh** [comment]
did not work for me...restarted everything...but no luck

**Comment by greghesp** [comment]
@namdoh @josharmour has this been disable again? It's not stopped working again

**Comment by josharmour** [comment]
Still working for me..  hmmm

**Comment by sbucaille** [comment]
@josharmour not working for me anymore, tried to install relay and still not working.
Do you think it does depend on language you put or something like that ?

**Comment by greghesp** [comment]
So 7:30 BST this morning, my front door opened, my relay picked up the command and sent the broadcast request.  Nothing happened, and My Activity didn't even log the request.  I tested with a request straight from Assistant on my phone and it worked

I've just opened my front door again, and its now working.  Relay picked up the command, send the broadcast request, logged it in My Activity and the broadcast command worked.

![image](https://user-images.githubusercontent.com/768908/42156095-0a96016e-7de2-11e8-8057-5f1459da29a1.png)

Seems like the API for Assistant is being a bit flakey @josharmour

**Comment by do1eh** [comment]
It logs everything perfectly on myactivity, but no sound on speakers since thursday..if I'm using the phone there's no problem at all.

**Comment by sbucaille** [comment]
@greghesp @do1eh Me too got everything in the logs, but everything coming from the SDK doesn't let GH to prompt it : 
![screenshot_20180702-143143](https://user-images.githubusercontent.com/24275548/42164129-4d74a8f0-7e05-11e8-8782-b0f4b8e1c42d.jpg)

**Comment by do1eh** [comment]
Maybe it's a location and/or language problem...UK works but France and Germany does not.

**Comment by greghesp** [comment]
I've had it on US and UK, both are intermittent

**Comment by Laupet** [comment]
Not working in Norway. Everything is logged in MyActivity

**Comment by hufftheweevil** [comment]
It's been working 100% for me ever since the fix.

**Comment by josharmour** [comment]
Folks who this is either not working for or it's being intermittent - is
your assistant-relay device in the same physical location as the Google
Homes that are being broadcasts too?  If so, are they on the same wireless
network and subnet?  I ask because some folks like to segregate devices or
have different networks for physically plugged in devices (via ethernet)
and clients connected to access points..

**Comment by Laupet** [comment]
They are on the same network for me.

**Comment by greghesp** [comment]
Same network and subnet for me

**Comment by do1eh** [comment]
Yes of course. It worked really well until Thursday 17:00 CET so the network is not the problem. For it is logged in myactivities it looks like the relay is doing everything correctly but then it is somehow blocked by Google. Maybe they don't like the way we 'abuse' their broadcast feature.

**Comment by esalomo** [comment]
The complete Google platform seems to be unstable / flakey in the past 2 weeks and from multiple interactions with the GH support team it seems like they do not have f#$& Clue what/where is the problem hence they are not ack. the fact there is a wide problem with the platform and trying to address each of us as individual issues - very dissapointing response from such giant tech :(

**Comment by namdoh** [comment]
Hi guys, I'm sorry to hear that feature stopped working for some of you.

For broadcast feature, ASSISTANT_SDK doesn't provide us needed information to determine if two devices are in same network.  We explored different options, and ended up with a heuristic solution that we believe would work for almost all ASSISTANT_SDK users.  However, judging from your feedback on this thread, there are still some gaps in the latest fix.

Can you help file bug report via your ASSISTANT_SDK device right after broadcast is initiated?  I would need to understand why it doesn't work with your setup.

**Comment by greghesp** [comment]
@namdoh how exactly would we file a bug report via the SDK?  Most of us here are using this module from endoplasmic, which I've wrapped an express server around to accept http requests

**Comment by namdoh** [comment]
@greghesp: Do you see your device in Home app?  If so, can you try to follow the instructions here: https://www.androidcentral.com/want-help-google-home-improve-heres-how-send-feedback

**Comment by greghesp** [comment]
@namdoh no device's in my Home app apart from the official Google Hardware

**Comment by ryancasler** [comment]
Still not working for me for the last week.  I'm in the US and all my devices are on the same network and subnet.  I did participate in the preview updates on my Google home which i have since unsubscribed to but haven't gotten the standard firmware pushed yet.  Don't know if that has anything to do with it.  I've tried going so far as re-installing node and relay and it still doesn't work.

**Comment by josharmour** [comment]
Hey @ryancasler would you mind working me to get a bug report?  Do you see
the device in the home app?  Are you using a Pi or some other assistant
device that shows up in the Google Home app?

**Comment by do1eh** [comment]
I have one home running the preview and a mini running the standard version, but none of them worked. As I understand that's not a firmware problem but the way the broadcast algorithm detects whether or not the devices are on the same network. I think we have to find out what's the difference between a working and a not working setup. My network is pretty standard. No fancy subnets and all homes including the raspberry pi running Google assistant relay connect to the same wifi. The only thing special is that in my provider provides IPV6 only. (DS-lite, that means no public IPV4 adress. If you want to connect to my network from the outside you have to use IPV6 ). Internally my LAN (including the wifi with the home devices) is running on IPV4.

**Comment by josharmour** [comment]
Hmm, is that the same for you @ryancasler?

**Comment by mhofman** [comment]
That makes me think that my network is dual homed and that the python assistant that wasn't working is running in a docker container that ends up being routed out of a different public IP than the rest of my network. When I ran `assistant-relay` which worked fine it was on machine in the local network. The docker container can reach the local network but has a different route out to the public internet.

**Comment by ryancasler** [comment]
It doesn't matter what network they are on.  They have to be signed on to the same account.  You can broadcast from the Home app on your phone when you're not connected to WiFi.  Give it a try.

That was the issue that google had with the broadcasts being part of the SDK in the first place.  You could have broadcasts running inadvertantly on Google Home devices that the user didn't want them broadcast on.  If you have a home device at work and one at home and both are signed into the same account, a broadcast command from the same google account will broadcast on both devices.  So, it doesn't matter if both are on the same subnet, different subnets or in some other country.  A broadcast command should play on all devices that are running on the same account.

**Comment by mhofman** [comment]
Home/Google app on phone and SDK behave differently as Google explained.
In the SDK they added heuristics to prevent broadcasting to different unintended locations.
I'd be ready to bet that the heuristics involve matching public IP addresses. Probably not subnet as that would have to be provided by the SDK, hence trusting user controlled information.

**Comment by ryancasler** [comment]
From troubleshooting for the SDK for devices:
Broadcast issues
The Assistant cannot broadcast messages from one device to the other.

Make sure to set the device location in the Google Assistant app. Both devices must have the same address in the app.

But the relay device doesn't show up in the app, so how are you supposed to assign it a location in the app?  That's the million dollar question.

**Comment by josharmour** [comment]
@namdoh designed it so he may be the best person to answer these magical
questions.

As far as I know, there is some logic based on ip address that is being
applied to determine of devices are in the same home - so things like ipv6
and different subnets could affect that logic.  Note, this logic addition
is recent.

**Comment by chriswalker01** [comment]
@namdoh Thanks for all the great work with this. Mine has been working perfectly since the feature was re-enabled a few Fridays ago.

I was wondering, do you know if there are any plans to release Google Mesh with Google Home built in? I have my Homes right next to the wifi points. It'd be good to compress them to one box.

To help others troubleshoot, I have Google Assistant on a different subnet to the Google Homes, but same public IP. Works every time without issue.

**Comment by phvajjha** [comment]
Anyone else wants to give it a try: I used this guide to manually create a device type and a device instance from my laptop - https://developers.google.com/assistant/sdk/reference/device-registration/register-device-manual

I then used the created device id and device type in the relevant config section of the google assistant relay app running on my raspberry pi.

The "device" shows up in the Google Home app under the Google Assistant section -> More Settings -> Devices. It also shows up in Home Control as a Virtual device and I can assign a room to it.

**Comment by namdoh** [comment]
@phvajjha: After following registration instruction, can you select the device when sending feedback?

If you don't see the device, it's ok to select "I don't see the device" and send feedback. In the subject, please mention broadcast on raspberry pi with assistant-relay.

In the meantime, we're exploring a long term solution that would be both more reliable and offer more customization.

**Comment by namdoh** [comment]
@chriswalker01: At my pay-grade, I can't reveal our product launch plan.  However, please keep voice up and ask for it :-)

**Comment by sbucaille** [comment]
@namdoh hi, any update news from this issue ? 
Is it working again since last time ? (Didn't have time to check it out)

**Comment by DaveMeade** [comment]
So I just got everything setup and my broadcasts are not being announced either.  Here are my observations: 

1. The relay device accepts the request, and processes them.
2. I see the request within "My Activity" in the Google home app.
3. No broadcast actually takes place.
4. The Google Cloud dashboard shows the requests received from the relay device
5. **The Google Cloud dashboard shows these requests resulted in _Error 499_** (seems to be a "canceled by user" error code - I didn't, of course, cancel anything).

I'm not sure if this is a result of the SDK changes, but I wanted to chime in.  @namdoh and @josharmour if there are details from the Cloud Console API Dashboard that would help, I'd be happy to try and provide them.

**Comment by ryancasler** [comment]
I get the following error when I attempt to install now which i never got before:
```
Paste your code: (node:19205) UnhandledPromiseRejectionWarning: Error: Exited with code 3
    at ChildProcess.cp.once.code (/home/pi/assistant-relay/node_modules/opn/index.js:84:13)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)
(node:19205) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19205) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Dunno what is causing that.  Could it be the version of Node that I'm trying to use?  I'm using 8.11.3.  Also, all of my activity is showing up in My Activity in google but not getting any broadcasts.

**Comment by greghesp** [comment]
@ryancasler that issue isn't anything to do with this. Can you open as an issue on my repo please and I'll take a lool

**Comment by ryancasler** [comment]
OMG.....so, I just got it work!!!  I had to disable the IPV6 on my netgear router.  I now get broadcasts on my google home devices.  It must have been thinking they were in different locations because of the IPV6 address being different.  HOLY CRAP!!!

**Comment by do1eh** [comment]
Uh that is a problem. When I disable Ipv6 I loose my internet connection because I have ipv6 only (and a ds lite tunnel for ipv4). I tried to disable ipv6 on the raspberry pi but no luck. I ask my self why everyone always forgets to implement ipv6 in their services. I even can't control my homebrew smarthome via GH because IFTTT webhooks do not support ipv6. Please google, please please please enable ipv6 support.

**Comment by JumpMaster** [comment]
There seems to be a bug in firmware 130671.  If night mode is enabled broadcasts stop working.  Do not disturb or the time of day has no effect.  It instantly stops working if night mode is enabled.

**Comment by DaveMeade** [comment]
UPDATE: based on @ryancasler 's post above, I disabled IPV6 on my router and restarted the relay ... and it works now.

It does appear that having IPV6 enabled on my LAN was the issue.  This is really unfortunate as I'm not convinced I can or wish to leave it disabled, but the good news is it appears that disabling IPv6 is a work around for those that can do so.

**Comment by ryancasler** [comment]
I have night mode enabled on my google home's and broadcasts are working just fine.  Obviously if do not disturb is enabled you won't get broadcasts.  That's kind of the whole point of "do not disturb" isn't it?

**Comment by JumpMaster** [comment]
Hi Ryan. I assume you're not on the for ware version I mentioned?

I also said that the do not disturb option does not have any effect. I've reported the bug to Google but the firmware has only been out for a couple of days on the preview programme.

**Comment by do1eh** [comment]
@namdoh are there any updates on this issue? Are you still working on this, including Ipv6 support?

**Comment by VPeeters** [comment]
My RPi uses VPN, while my Google Home and Chromecast do not. If I understand correctly, the reason I am unable to broadcast and to control my Chromecast might be that they have a different public IP address?

**Comment by dherran** [comment]
On top of the IPV6 support, what if the SDK is installed in a server outside the network? for example, I have the SDK installed in a web server running node that I use for [assistant-relay](https://github.com/greghesp/assistant-relay/)

**Comment by ryancasler** [comment]
The requirement is that your device running the assistant SDK must be resident with the other devices you want to Broadcast to.  Google did that to address privacy concerns with the broadcast feature so I doubt they are going to change it anytime soon.

**Comment by chriswalker01** [comment]
@pet125 I believe the device running the assistant and the other devices need to have the same public IP address. This generally means that they need to be in the same house/workplace/residence etc.

**Comment by michaelarnauts** [comment]
Has anyone got this to work with an active IPV6 connection on the LAN side? Google should be smart enough to see that a request is from the same /64 subnet, so that it should be in the same location, right?

**Comment by greghesp** [comment]
Hi @namdoh 

It looks like the IPV6 issue is still causing quite a few issues, especially for those than can't turn it off.

Are there any plans for a workaround on this? I don't know what heuristics you've put in place, but if I made it so that it registered Assistant Relay as a device and then users assigned that to their home in the Google Home app, would that force the broadcasts as they're part of the same home?
