### ISSUE TITLE
Failed to npm install google-assistant

### ISSUE THREAD

**Issue by cben0ist** [endoplasmic/google-assistant#54]
When trying to install google assistant I have the following errors:

> ➜  assistant-relay git:(master) npm install google-assistant
> 
> > grpc@1.8.0 install /home/cben0ist/assistant-relay/node_modules/grpc
> > node-pre-gyp install --fallback-to-build --library=static_library
> 
> node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.8.0/node-v64-linux-x64-glibc.tar.gz 
> node-pre-gyp ERR! Pre-built binaries not found for grpc@1.8.0 and node@10.2.1 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
> node-pre-gyp ERR! Tried to download(undefined): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.8.0/node-v64-linux-x64-glibc.tar.gz 
> node-pre-gyp ERR! Pre-built binaries not found for grpc@1.8.0 and node@10.2.1 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
> make: Entering directory '/home/cben0ist/assistant-relay/node_modules/grpc/build'
> make: Entering directory '/home/cben0ist/assistant-relay/node_modules/grpc/build'
>   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
>   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
>   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/backoff/backoff.o
> sed: can't read ./Release/.deps/Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o.d.raw: No such file or directory
> rm: cannot remove './Release/.deps/Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o.d.raw': No such file or directory
> grpc.target.mk:386: recipe for target 'Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o' failed
> make: *** [Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o] Error 1
> make: Leaving directory '/home/cben0ist/assistant-relay/node_modules/grpc/build'
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
> gyp ERR! System Linux 4.4.0-128-generic
> gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/home/cben0ist/assistant-relay/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/home/cben0ist/assistant-relay/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc"
> gyp ERR! cwd /home/cben0ist/assistant-relay/node_modules/grpc
> gyp ERR! node -v v10.2.1
> gyp ERR! node-gyp -v v3.6.2
> gyp ERR! not ok 
> node-pre-gyp ERR! build error 
> node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/home/cben0ist/assistant-relay/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/cben0ist/assistant-relay/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc' (1)
> node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/cben0ist/assistant-relay/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
> node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
> node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
> node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
> node-pre-gyp ERR! System Linux 4.4.0-128-generic
> node-pre-gyp ERR! command "/usr/local/bin/node" "/home/cben0ist/assistant-relay/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
> node-pre-gyp ERR! cwd /home/cben0ist/assistant-relay/node_modules/grpc
> node-pre-gyp ERR! node -v v10.2.1
> node-pre-gyp ERR! node-pre-gyp -v v0.6.39
> node-pre-gyp ERR! not ok 
> Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/home/cben0ist/assistant-relay/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/cben0ist/assistant-relay/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc' (1)
>   CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_args.onstall script
> make: *** No rule to make target '../deps/grpc/src/core/lib/channel/channel_stack.cc', needed by 'Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_stack.o'.  Stop.
> make: Leaving directory '/home/cben0ist/assistant-relay/node_modules/grpc/build'
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
> gyp ERR! System Linux 4.4.0-128-generic
> gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/home/cben0ist/assistant-relay/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/home/cben0ist/assistant-relay/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc"
> gyp ERR! cwd /home/cben0ist/assistant-relay/node_modules/grpc
> gyp ERR! node -v v10.2.1
> gyp ERR! node-gyp -v v3.6.2
> gyp ERR! not ok 
> npm WARN assistant-relay@1.0.1 No repository field.
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! grpc@1.8.0 install: `node-pre-gyp install --fallback-to-build --library=static_library`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the grpc@1.8.0 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Any help is appreciated. 
Thank you

**Comment by endoplasmic** [comment]
What are you trying to install this on? linux, mac, windows, sandwich?

**Comment by cben0ist** [comment]
Good question. Ubuntu 16.04 LTS

**Comment by endoplasmic** [comment]
Sadly I've got to head out for the next week-ish, but I'll see about
spinning up a VM and giving that a whirl (unless someone else gets to it
before then)

**Comment by cben0ist** [comment]
OK, that was definitely my node version. I should not have updated to other than LTS. I will know now...
Thank you all for your help.
