### ISSUE TITLE
No response for Home Control status questions

### ISSUE THREAD

**Issue by Harel-M** [endoplasmic/google-assistant#56]
Hi,
Sending commands to Home Control devices is working fine, I can send a query "turn X on" and the device will turn on.
But when sending a query "is X on?" i'm getting a blank response from the assistant.
The same query sent via google home or the google assistant on the phone is working properly.

What can be the reason for this?

Thanks,

**Comment by Harel-M** [comment]
I noticed that also for other Home Control commands (turn on, turn off), I don't see the assistant response.
It does the action (turning on/off) but I don't get the response on the console... it is less important though, the status answer is more critical...

**Comment by Fleker** [comment]
This is a limitation of the Assistant SDK.
