### ISSUE TITLE
mic-speaker.js keeps returning 'service unavailable'?

### ISSUE THREAD

**Issue by stephenxp04** [endoplasmic/google-assistant#57]
Hi im trying to implement a web based voice google assistant. However the mic-speaker.js sample cant seem to record my voice input at all. I have tried recording with node-record-lpcm16 sample alone and it is able to record my voice fine. Can anyone provide any insight to this? Thanks!

Updated:
So I did some testing with the record module itself with verbose set true and found out that the recording ended abruptly even before I speak anything resulting in no audio input into the Google Assistant request at all. I have used the same settings as node-record-lpcm16 README and sample suggested but still have no luck of capturing my voice recording. Help is appreciated!

**Comment by motorvor** [comment]
I'm having this issue as well, has anyone had any luck with this? In my scenario, I'm converting a 32 bit PCM stream into the 16bit PCM stream that the api requires. yet I'm still getting "Error: 14 UNAVAILABLE: Service unavailable." I'm unsure what could be causing this.

**Comment by RocoGreen** [comment]
Hello, i have this issue too and i have a 16 bit PCM stream (16000) on event data to get the chunks (buffer) but when he write the buffer, the event data is stucked and repeated and finally crash with 14 UNAVAILABLE: Service unavailable. I think it's a bug but i dont know why it's doing this. Please help me

**Comment by endoplasmic** [comment]
Can you guys get me some more information about node version and operating system? I just tried the `mic-speaker.js` example and it worked fine. I'm also sending 16bit PCM data for streaming speech to text.

**Comment by RocoGreen** [comment]
For me i have windows 10 on node 11.6.0 and i have retried and same error. Maybe the module doesnt working on node v11. If yes, i dont know why it's causing this.

**Comment by dang1412** [comment]
it seems `14 UNAVAILABLE: Service unavailable` happens a lot, even when the text transcriptor comes fine, I think that is the issue relating recording and sending audio input.

Is it possible to use python to send audio input and node listen to the command only?

**Comment by Melvin-Abraham** [comment]
There's a workaround for this which _might not be ideal_. Simply navigate to `node_modules\node-record-lpcm16\recorders\sox.js` & add `'-t', 'waveaudio'` in the args variable. It should look like:

```js
let args = [
    '-t', 'waveaudio', // ADDED THIS LINE
    '--default-device',
    '--no-show-progress', // show no progress
    '--rate', options.sampleRate, // sample rate
    '--channels', options.channels, // channels
    '--encoding', 'signed-integer', // sample encoding
    '--bits', '16', // precision (bits)
    '--type', options.audioType, // audio type
    '-' // pipe
]
```
