### ISSUE TITLE
'ended' should auto fire when there is no voice response

### ISSUE THREAD

**Issue by ppisljar** [endoplasmic/google-assistant#6]
In some cases google will not respond anything to your command 
(for example when you say 'hey google, volume 5')

in this scenario no voice data will be received, the speaker will not get opened, and nothing will fire the conversation.end()

for such scenarios 'ended' event should probably auto fire. ('no voice response' should be detected by the lib ... as there seems to  be no way of detecting it on my end)

**Comment by endoplasmic** [comment]
Solid find!

I went deep digging, but ended up just triggering the `end()` method whenever we need to change the volume.

**Comment by ppisljar** [comment]
I am sure there are more cases like this, so detecting google's response would be the right way to go.
imagine something like `google, turn on the light` (light comes on, no voice response ....)

**Comment by endoplasmic** [comment]
Does that happen for you? Whenever I do it, she always replies with something like "Okay, turning on xxxxx light" or "Turning on 2 lights", something like that.

Yah, I agree with you though, I need to find out if the python version handles it differently, but I have to admit that my python skills are pretty rough.

**Comment by ppisljar** [comment]
one (not the best) way would be with a timeout (if in 100ms after end of utterance first audio packet is not received we end the conversation) ....

**Comment by endoplasmic** [comment]
If you wanted to implement something like that, you could do it on your server. 

Start a timeout once you get `transcription-complete` that fires `conversation.end()`. `clearTimeout` when you get the `audio-data` event.

I'm not a huge fan of implementing a timeout since we don't know much about network traffic, but at least with the events that are fired, you can implement it.

**Comment by ppisljar** [comment]
i am looking at the way its done in python sample app ...  https://github.com/googlesamples/assistant-sdk-python/blob/master/google-assistant-sdk/googlesamples/assistant/grpc/pushtotalk.py#L109

there is no extra condition anywhere, it just loops over the response packets then ends the conversation, so seems there is a clear notification from the server when the last packet was sent.

looking at the comment in https://github.com/googleapis/googleapis/blob/master/google/assistant/embedded/v1alpha1/embedded_assistant.proto#L255

```
// This event indicates that the server has detected the end of the user's
    // speech utterance and expects no additional speech. Therefore, the server
    // will not process additional audio (although it may subsequently return
    // additional results). The client should stop sending additional audio
    // data, half-close the gRPC connection, and wait for any additional results
    // until the server closes the gRPC connection.
``` 

also seems to suggest that the stream will be closed after last packet is sent ?

**Comment by endoplasmic** [comment]
Yah, I get a bit lost in the python stuff sadly. Could use a hand getting through that.

As far as your second link, that's actually only to tell you that the user is finished speaking and to not send any more audio to the server. Once you get that message, you'll get the audio (if there is any) right after that.

**Comment by ppisljar** [comment]
yeah, the function does that, but the comment seems to suggest that the server will close gRPC connection  after its done sending data ?

`..., and wait for any additional results until the server closes the gRPC connection.`

https://developers.google.com/assistant/sdk/reference/library/python/   ... the python library seems to provide more events, one of them being 
```
ON_NO_RESPONSE = 8
The Assistant successfully completed its turn but has nothing to say.
```

but the same doesn't look to be available in the gRPC api ...
