### ISSUE TITLE
broadcast audio file

### ISSUE THREAD

**Issue by mduzgun** [endoplasmic/google-assistant#67]
I want to send audio file to my physical google home mini device,  so I try to use broadcast feature.
When I give audio data, if there is silence in audio data, I don't send audio after silence. Only starting part can be sent. I want to send whole sound.
How to configure silence timeout for audio command? Or is there another way?

**Comment by endoplasmic** [comment]
The silence would have to be pretty long I'm guessing. The Automatic Speech Recognition (ASR) determines when there is enough silence to assume the query is over.

I don't have any insight into that, but I don't think there is a way to ignore silence when making a request.
