### ISSUE TITLE
Just Finished Auth Crash

### ISSUE THREAD

**Issue by CTKRocks** [endoplasmic/google-assistant#7]
After I authenticate, it says:
```shell
Say something!
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn rec ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)
```

What causes this?

(i'm running the mic and speaker example)

**Comment by CTKRocks** [comment]
`brew install sox` solved the issue. Maybe put the `node-record-lpcm16` dependencies in the Readme next to where you tell about the speaker macOS error?

**Comment by endoplasmic** [comment]
Glad you got it sorted out!

I do link to [`node-record-lpcm16`](https://github.com/gillesdemey/node-record-lpcm16) from the readme. Under the dependencies on that page it says to type `brew install sox`.

**Comment by CTKRocks** [comment]
Yes. I was suggesting you put that command on your Readme under the part about MacOS, but you don’t have too. 👍
		
Just nice to stay on the same page. 

		Get Outlook for iOS
	





On Wed, Jun 28, 2017 at 4:14 PM -0400, "Scott" <notifications@github.com> wrote:












Glad you got it sorted out!


I do link to node-record-lpcm16 from the readme. Under the dependencies on that page it says to type brew install sox.
