### ISSUE TITLE
Pass json data rather than a file?

### ISSUE THREAD

**Issue by greghesp** [endoplasmic/google-assistant#71]
Is there a way to pass the token and secret json objects as a location in something like lowdb or similar?

I'm trying to implement refresh my Assistant Relay to make it more user friendly, and would be great if i could just pass the JSON data rather than a file

**Comment by endoplasmic** [comment]
I think if you go down that road, it's probably easier for you to create your own google authed client and pass it in as `oauth2Client` in the config.

**Comment by greghesp** [comment]
Yep that's what I ended up doing. I then just required your conversation component directly

`const Conversation = require('google-assistant/components/conversation')`
