### ISSUE TITLE
Typings for AuthConfig do not support OAuth2Client field

### ISSUE THREAD

**Issue by pauleeeeee** [endoplasmic/google-assistant#74]
(Thank you for this library)

The docs say:

> You may also pass in your own OAuth2 client via the oauth2Client param (This will be used instead of keyFilePath and savedTokensPath). See the usage below for an example.

But I cannot do this in a strict TypeScript environment because the typings.d.ts file has not been updated to reflect this functionality

**Comment by endoplasmic** [comment]
I accept PRs :D

**Comment by pauleeeeee** [comment]
I am sorry to say that I have almost no git experience and have no idea how to do that successfully. I am terrified of touching someone else's code LOL. When I learn how I will be sure to submit one.

**Comment by endoplasmic** [comment]
Oh it's not too bad really!

On the top right, hit the "Fork" button. It'll clone this repo to your own account. Once you clone *that* repo, make changes (add files, etc.) and then hit the pull request button:

![image](https://user-images.githubusercontent.com/118301/74129119-a2185200-4b93-11ea-81d6-0ba715a8cf19.png)

Once you do that, I'll get a notification that there is one. I can review the code, put feedback, etc. and then I just merge it into the main one here :)

**Comment by pauleeeeee** [comment]
Thank you sensei
