### ISSUE TITLE
Handling of refresh token?

### ISSUE THREAD

**Issue by paulembleton** [endoplasmic/google-assistant#75]
Does this library automatically handle refreshing the user's access token if the token is expired? It does not seem that way. More context:

Environment: Google Cloud Function
Status: Works until access token expires. Then, invocations of the cloud function fail due to invalid credentials. 
Other information:
- I have properly configured the two JSON files for credentials and tokens.
- Library works as expected until access token expires
- tokens.json includes a valid refresh token in the customary refresh_token field

**Comment by endoplasmic** [comment]
The library does handle the auto refreshing of tokens.

What happens when you try to start a new session when the token expires? I've never seen this happen (and I've had an instance of this running on a server for months).

Can you paste the error the next time you get it? I'm going to start a session and let it sit there and see what happens when I try again in an hour or so.

**Comment by paulembleton** [comment]
Thanks for your response. Here is the error:
`Conversation Error: { Error: 16 UNAUTHENTICATED: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
    at Object.exports.createStatusError (/srv/node_modules/grpc/src/common.js:91:15)
    at ClientDuplexStream._emitStatusIfDone (/srv/node_modules/grpc/src/client.js:233:26)
    at ClientDuplexStream._receiveStatus (/srv/node_modules/grpc/src/client.js:211:8)
    at Object.onReceiveStatus (/srv/node_modules/grpc/src/client_interceptors.js:1311:15)
    at InterceptingListener._callNext (/srv/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/srv/node_modules/grpc/src/client_interceptors.js:618:8)
    at /srv/node_modules/grpc/src/client_interceptors.js:1127:18
  code: 16,
  metadata: Metadata { _internal_repr: { 'www-authenticate': [Array] }, flags: 0 },
  details: 'Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.' }`

I think it has to do with the fact that I am not passing an oAuth2Client object... although I wish too but can't because of typings file doesn't specify it...?

**Comment by endoplasmic** [comment]
no no, oAuth2Client is optional (you can see in the example files), it's just another way to use the regular Google OAuth (say from a web sign-in) without having to ask the user to auth again.

Mind pasting some of your code? I didn't create the typings file (was a PR), but I'm happy to look at what you've got to see if I can find anything out of wack.

**Comment by paulembleton** [comment]
Thanks for your response again
Here is my code:
`import * as functions from 'firebase-functions';
import { google } from 'googleapis';
const OAuth2 = google.auth.OAuth2; 
import {resolve} from 'path';

// const googleAssistantCredentials = require('../src/credentials.json');
// const googleAssistantTokens = require('../src/googleAssistantTokens.json');

const authConfig = {
    keyFilePath: resolve(__dirname,'../src/googleAssistantCredentials.json'),
    savedTokensPath: resolve(__dirname,'../src/googleAssistantTokens.json')
}

import GoogleAssistant = require("google-assistant");


export const googleAssistant = functions.https.onRequest((request, response)=>{

    if (request.body.command){

        var command = request.body.command;
        const conversation = {
            isNew:true,
            textQuery:command 
        }

        const startConversation = (conversation:any) => {
            conversation
                .on('response', (text:any) => {
                    console.log('Assistant Text Response:', text);
                    response.status(200).send(text);
                })
                .on('screen-data', (screen:any) => {
                    // if the screen.isOn flag was set to true, you'll get the format and data of the output
                    console.log(JSON.stringify(screen))
                  })
                .on('error', (error:any) => {
                    console.log('Conversation Error:', error);
                    response.status(200).send('failed');
                  });
        }

        const assistant: GoogleAssistant = new GoogleAssistant(authConfig);

        assistant.on('ready', () => {
            // start a conversation!
            assistant.start(conversation);
          })
          .on('started', startConversation)
          .on('error', (error:any) => {
            console.log('Assistant Error:', error);
            response.status(200).send('failed');
          });

    } else {
        console.log('error no command received')
        response.status(200).send('failed');
    }
});

`

**Comment by paulembleton** [comment]
Maybe because I am declaring the auth config outside the scope of the cloud function?

**Comment by endoplasmic** [comment]
Your code pasted a bit wacky, but it looks like you're going new GoogleAssistant each time there is a new request. You only need to init it once and then your startConversation call should happen on the request.

**Comment by paulembleton** [comment]
Yeah sorry about the formatting - I tried to fix it but it just wouldn't take. Thanks for the idea. I will move the init to the global scope outside of the cloud function, re-up my credentials, and try again.

**Comment by endoplasmic** [comment]
so for formatting, wrap it in tripple tick ` ` ` (without the spaces)

**Comment by endoplasmic** [comment]
Just wanted to check in to see how you made out. Moving the `new GoogleAssistant` out of the request fix things up?

**Comment by paulembleton** [comment]
Hi endoplasmic,

So I moved the instantiation out of the function scope, but that means that the function could not receive the "ready" event (which means the callback to start did not fire). So I instead called the assistant.start() function which worked just fine. However, after one hour, I still got the unauthenticated error. I think it has to do with the way that your Auth module refreshes the token. I am using Firebase and I am just not sure that the tokens are refreshed and saved to the global memory of my Firebase instance. So, I used the oAuth2Client library to update my tokens myself on each function invocation (if necessary). Then I modified the index.d.ts file in your library to allow me to pass the oAuth2Client object. This worked for me. I would suggest configuring the library to allow the user to pass the oAuth2Client object. I know that you have done this in JS but, as I mentioned, you cannot do so in a strict TypeScript environment.

Hope that gives you some ideas... and thank you for this library and all of your help!

**Comment by endoplasmic** [comment]
Glad you got it sorted. Would you mind doing a PR on that index file? That way others in your shoes can benefit!

**Comment by paulembleton** [comment]
It would be my very first pull request ever... So... Just be warned LOL

**Comment by ImMALWARE** [comment]
@endoplasmic 
Maybe I'm too late, but here is my implementation of handling refresh token. I modified library files. auth.js:
```js
'use strict';

const EventEmitter = require('events');
const util = require('util');
const open = require('open');
const readline = require('readline');
const fs = require('fs');
const path = require('path');
const mkdirp = require('mkdirp');
const { OAuth2Client } = require('google-auth-library');

function Auth(config) {
  if (config === undefined) config = {};

  // make sure we have a key file to read from
  if (config.keyFilePath === undefined) {
    throw new Error('Missing "keyFilePath" from config (should be where your JSON file is)');
  }

  if (config.savedTokensPath === undefined) {
    throw new Error('Missing "savedTokensPath" from config (this is where your OAuth2 access tokens will be saved)');
  }

  const keyData = require(config.keyFilePath);
  const key = keyData.installed || keyData.web;
  const oauthClient = new OAuth2Client(key.client_id, key.client_secret, key.redirect_uris[0]);
  let tokens;

  const saveTokens = () => {
    oauthClient.setCredentials(tokens);
    this.emit('ready', oauthClient);

    // save them for later
    mkdirp(path.dirname(config.savedTokensPath))
      .then(() => {
        fs.writeFileSync(config.savedTokensPath, JSON.stringify(tokens, null, 2));
      })
      .catch((error) => {
        console.log('Error saving tokens:', error.message);
      });
  };

  // Refreshing access token
  const refreshAccessToken = async () => {
    try {
      const refreshedTokens = await oauthClient.refreshAccessToken();
      tokens = refreshedTokens.credentials;
      saveTokens();
    } catch (error) {
      console.error('Error refreshing access token:', error.message);
      process.exit(-1);
    }
  };

  // Do we need to refresh access token?
  this.ensureValidTokens = async () => {
    if (!tokens.expiry_date || tokens.expiry_date <= Date.now()) {
      console.log('Access token expired. Refreshing...');
      await refreshAccessToken();
    } else {
      oauthClient.setCredentials(tokens);
      this.emit('ready', oauthClient);
    }
  };

  const getTokens = () => {
    const url = oauthClient.generateAuthUrl({
      access_type: 'offline',
      prompt: 'consent', // else refresh token just won't be returned
      scope: ['https://www.googleapis.com/auth/assistant-sdk-prototype'],
    });

    // open the URL
    console.log('Opening OAuth URL. Return here with your code.');
    open(url).catch(() => {
      console.log('Failed to automatically open the URL. Copy/paste this in your browser:\n', url);
    });

    // if tokenInput is configured
    // run the tokenInput function to accept the token code
    if (typeof config.tokenInput === 'function') {
      config.tokenInput(processTokens);
      return;
    }

    // create the interface to accept the code
    const reader = readline.createInterface({
      input: process.stdin,
      output: process.stdout,
      terminal: false,
    });

    reader.question('Paste your code: ', processTokens);
  };

  const processTokens = (oauthCode) => {
    if (!oauthCode) process.exit(-1);

    // get our tokens to save
    oauthClient.getToken(oauthCode, (error, tkns) => {
      // if we have an error, print it and kill the process
      if (error) {
        console.error('Error getting tokens:', error.response.data);
        process.exit(-1);
      }

      // if we didn't have an error, save the tokens
      tokens = tkns;
      saveTokens();
    });
  };

  // if the tokens are already saved, we can skip having to get the code for now
  process.nextTick(async () => {
    if (config.savedTokensPath) {
      try {
        const tokensFile = fs.readFileSync(config.savedTokensPath);
        tokens = JSON.parse(tokensFile);
      } catch (error) {
        // we need to get the tokens
        getTokens();
      } finally {
        if (tokens !== undefined) saveTokens();
      }
      if (tokens) {
        await this.ensureValidTokens();
      }
    } else {
      getTokens();
    }
  });

  return this;
}

util.inherits(Auth, EventEmitter);
module.exports = Auth;

```


index.js:
```js
'use strict';

const EventEmitter = require('events');
const util = require('util');

const Assistant = require('./components/assistant');
const Auth = require('./components/auth');
const Conversation = require('./components/conversation');

function GoogleAssistant(authConfig, callback) {
  if (authConfig === undefined) {
    const error = new Error('Missing auth config object!');
    this.emit('error', error);
    if (callback) callback(error);
    return;
  }

  let assistant;

  const assistantReady = () => {
    if (assistant) {
      this.emit('ready', assistant);
      if (callback) callback(assistant);
    }
  };

  if (authConfig.oauth2Client) {
    // we are passing in a client that is already authed with Google
    assistant = new Assistant(authConfig.oauth2Client);
    process.nextTick(assistantReady);
  } else {
    // we need to auth with Google right out of the gate
    const auth = new Auth(authConfig);

    auth.on('ready', (client) => {
      assistant = new Assistant(client);
      assistantReady();
    });

    this.auth = auth;
  }

  this.start = (conversationConfig, callback) => {
    if (assistant === undefined) {
      const error = new Error('Tried calling start() before the ready event!');
      this.emit('error', error);
      if (callback) callback(error);
      return;
    }

    this.auth.ensureValidTokens()
      .then(() => {
        const conversation = new Conversation(assistant, conversationConfig);
        this.emit('started', conversation);
        if (callback) callback(conversation);
      })
      .catch((error) => {
        this.emit('error', error);
        if (callback) callback(error);
      });
  };

  return this;
}

util.inherits(GoogleAssistant, EventEmitter);
module.exports = GoogleAssistant;
```
