### ISSUE TITLE
.on('response') no longer providing text?

### ISSUE THREAD

**Issue by greghesp** [endoplasmic/google-assistant#81]
I've had a few users mention this to me, and I've started to experience this more myself lately.  I've tried both en-US and en-GB languages.

Having asked questions such as

- What time is it?
- What's the weather in London?
- Who is the president of the USA?
- How tall is the Empire State Building?

none of them provide a text response, however all of them are proving audio responses.  
Not sure if Google have changed how the Assistant SDK responds, or if they've changed something else....

```
.on('response', text => {
   console.log(text)
}
```

**Comment by endoplasmic** [comment]
The proto hasn't changed in 16 months: https://github.com/googleapis/googleapis/blob/master/google/assistant/embedded/v1alpha2/embedded_assistant.proto

Hopefully this is just a short term problem, but "what time is it" used to always return text for me, but now it's not... Wonder what they are cooking up over there by breaking this :(

**Comment by greghesp** [comment]
I saw that earlier and actually reported this over here:
https://github.com/googlesamples/assistant-sdk-nodejs/issues/13

No where else to report it :/

**Comment by greghesp** [comment]
@endoplasmic Where about in the world are you located?  Google can't find the issue, however I suspect this might be regional..

**Comment by bugsounet** [comment]
Hi, don't forget this things :
It's an Google Assistant SDK project (+/- demo).

I have this issue a few months before and a few later day, it's be corrected (in France)
So i think it's not an issue for this repo. Just google do some test and forget to adjust a piece of code
just wait and see ;)

**Comment by greghesp** [comment]
@bugsounet I'm in contact with Google and they're unable to see an issue, although I'm still experiencing it. Trying to figure out if there is a pattern, as it's been like this for a solid week for me.

**Comment by greghesp** [comment]
@endoplasmic Can you test something for me please?  I think I might have figured out the cause of the issue.
It seems that by setting
```
    "screen": {
      "isOn": true
    }
```

It disables the text output.  I'm not sure if this is something your module is doing, or something the SDK is doing.

**Comment by endoplasmic** [comment]
I ran the `console-input` example and set the isOn (both true and false) with the query "what time is it" and no text was returned.

Even tracing all of the data events returns just the dialog state and audio buffer.
```
AssistResponse {
  speechResults: [],
  dialogStateOut:
   DialogStateOut {
     conversationState:
      <Buffer 0a 26 43 23 35 66 33 39 62 33 36 64 2d 30 30 30 30 2d 32 36 36 33 2d 39 62 34 38 2d 38 38 33 64 32 34 66 35 38 65 36 63 12 f6 01 4b 6a 38 30 4f 58 52 ... >,
     microphoneMode: 1 } }
```

It's missing the `supplementalDisplayText` param

This is a server side change that I don't have any control over :(

**Comment by bugsounet** [comment]
You can get the text in the 'screen-data' response (screenOutput)

I do this in js (extract of my code):
response.screen.originalContent is `screen-data` value
```js
      var ret = HTMLParser.parse(response.screen.originalContent)
      var dom = ret.querySelector(".popout-content")
      if (dom) response.screen.text = dom.structuredText
```
If it can help ;)

@endoplasmic : I know this bug since November, Maybe it's maybe wanted by google ?
```
    "screen": {
      "isOn": true
    }
```
so text is not required, maybe the logical by google.

**Comment by greghesp** [comment]
Any chance @endoplasmic  and @bugsounet  you can "me too" this issue, and pop in your code snippet:
https://github.com/googlesamples/assistant-sdk-nodejs/issues/13

**Comment by endoplasmic** [comment]
@bugsounet - The text wasn't consistent in the replies. Sometimes it would return it (what time is it) and other times it wouldn't (where is the nearest flower shop), but it was always the same. Now it seems that it straight up doesn't work at all. I haven't tried your screen scraping technique, but that's a clever work around!

@greghesp - Hit it with a 👍

**Comment by greghesp** [comment]
Cheers @endoplasmic.

I agree, it's never consistent. For me "What time is it?", just responds with a space: " ", whereas if there is no text response, i get an empty string :/

**Comment by endoplasmic** [comment]
Going through some older issues, and wanted to circle back on this... I went ahead and tried "What time is it" and I am getting a text response, is it still busted for you?
```
Type your request: what time is it
Assistant Response: It's 11:30 PM.
Conversation Complete
```
