### ISSUE TITLE
Where's the changelog?

### ISSUE THREAD

**Issue by fcastilloec** [endoplasmic/google-assistant#83]
This is a great project and I've been using it for a couple of months now without a problem. I recently saw that there's a new patch version and I was wondering what changed.
When I don't see a changelog on a repository, I usually try to compare between tags but the tags on Github are not the same as the ones over at npm.
Is it possible to provide a basic changelog? or a way to compare between releases?

**Comment by endoplasmic** [comment]
If you want to browse things a little, you could always hit up the [commits](https://github.com/endoplasmic/google-assistant/commits/master) and you'll see the tag names right at the top dividing each release.

Hope that helps :)
