### ISSUE TITLE
mic-speaker - TypeError: record.start is not a function

### ISSUE THREAD

**Issue by cyrild84** [endoplasmic/google-assistant#84]
Hi, I got this error with mic-speaker, after enter my OAuth code :
Say something!
/home/pi/******/node_modules/google-assistant/examples/mic-speaker.js:55
 const mic = record.start(...
TypeError: record.start is not a function

I might have found a similar issue on node-record-lpcm16 repo [link](https://github.com/gillesdemey/node-record-lpcm16/issues/59)
but not very familiar with type script.
Thanks

**Comment by endoplasmic** [comment]
Hmm, have never seen that before...

In the package.json, you should be using my fork:
```json
"devDependencies": {
    "node-record-lpcm16": "git+https://github.com/endoplasmic/node-record-lpcm16.git",
    "speaker": "^0.4.2"
  }
```

**Comment by bugsounet** [comment]
@endoplasmic : That does not surprise me

the original `node-record-lpcm16` is so buggy everyone needs their own code! ([mine](https://github.com/bugsounet/lpcm16/blob/master/index.js))

**Comment by cyrild84** [comment]
Thanks, problem solved.

**Comment by Allakazan** [comment]
Anyone there is an Typescript alternative ? I can't find a library that fits into my project lol
