### ISSUE TITLE
TypeError: google_credential.getRequestMetadata is not a function

### ISSUE THREAD

**Issue by aliasosx** [endoplasmic/google-assistant#90]
Hi , I try to use this library but I got error when runinig 

**TypeError: google_credential.getRequestMetadata is not a function**

below my package.json

{
  "name": "gAssistControl",
  "version": "1.0.0",
  "description": "",
  "main": "server.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "google-assistant": "^0.6.4",
    "googleapis": "^68.0.0"
  }
}
Could you advice?

**Comment by endoplasmic** [comment]
Could you post a bit more of your code? I'd like to see how you are calling the library.

**Comment by fcastilloec** [comment]
The problem might be with `google-auth-library` since `googleapis` installs a more recent version, and your project might be accessing the version installed by this module and that old version might not have that function.
