### ISSUE TITLE
It returns `invalid_grant` after a few days

### ISSUE THREAD

**Issue by Aymkdn** [endoplasmic/google-assistant#95]
Hi,

I configured everything and it worked great… but after a few days it stopped working and the program now returns an `invalid_grant`. I changed nothing on my side, so I'm wondering what could cause this issue? 

> Auth error:Error: invalid_grant
> Conversation Error: Error: 14 UNAVAILABLE: Getting metadata from plugin failed with error: invalid_grant

Before spending time redoing the whole registration and oauth process, I wanted to make sure it won't happen again in a few days?!

Thanks

**Comment by bugsounet** [comment]
Hi, I test your patch, the result is the same:
`Error: invalid_grant` invoqued by `oauthClient.refreshAccessToken()` line

**Comment by Aymkdn** [comment]
It might be because the project is in test and the refresh token is only valid during 7 days. I've been told to publish the project... I tried to publish it in alpha mode but the Google Console website returned an error. I wanted to try again later and see if it's enough.... So it might not be an issue with this library.

**Comment by Aymkdn** [comment]
[On this page](https://developers.google.com/identity/protocols/oauth2#expiration), it says:
> A Google Cloud Platform project with an OAuth consent screen configured for an external user type and a publishing status of "Testing" is issued a refresh token expiring in 7 days.

I tried to publish my project to "alpha" channel but it returns an useless error and now I'm stuck...

**Comment by Aymkdn** [comment]
OK, actually I think it's from this screen: https://console.cloud.google.com/apis/credentials/consent?project=PROJECT_NAME

There is "Publication State", and it's correctly in "testing". From there you can click on the publish button.

**Comment by endoplasmic** [comment]
I had the same error and after going down a rabbit hole, it looks like Google changed how OAuth worked. Your OAuth consent screen should look like this:
![image](https://user-images.githubusercontent.com/118301/118231055-8f5a9000-b45c-11eb-81be-d1b5d227bb83.png)

I then deleted my `tokens.json` file _(or whatever you have set in `savedTokensPath`)_, reran the script, did the OAuth flow, and now things are running fine.

Also just to double check, you need to make sure you've got the API enabled as well: https://console.cloud.google.com/marketplace/product/google/embeddedassistant.googleapis.com?q=search&referrer=search&project=PROJECT_ID_HERE

**Comment by Aymkdn** [comment]
Thanks. It should be good with my last comment.
